-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2014.4
-- Copyright (C) 2014 Xilinx Inc. All rights reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity image_filter_Block_Mat_exit1220_proc1 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    p_read : IN STD_LOGIC_VECTOR (11 downto 0);
    p_read2 : IN STD_LOGIC_VECTOR (11 downto 0);
    p_read16 : IN STD_LOGIC_VECTOR (11 downto 0);
    p_read17 : IN STD_LOGIC_VECTOR (11 downto 0);
    p_src_data_stream_0_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    p_src_data_stream_0_V_empty_n : IN STD_LOGIC;
    p_src_data_stream_0_V_read : OUT STD_LOGIC;
    p_src_data_stream_1_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    p_src_data_stream_1_V_empty_n : IN STD_LOGIC;
    p_src_data_stream_1_V_read : OUT STD_LOGIC;
    p_src_data_stream_2_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    p_src_data_stream_2_V_empty_n : IN STD_LOGIC;
    p_src_data_stream_2_V_read : OUT STD_LOGIC;
    src0_data_stream_0_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    src0_data_stream_0_V_full_n : IN STD_LOGIC;
    src0_data_stream_0_V_write : OUT STD_LOGIC;
    src0_data_stream_1_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    src0_data_stream_1_V_full_n : IN STD_LOGIC;
    src0_data_stream_1_V_write : OUT STD_LOGIC;
    src0_data_stream_2_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    src0_data_stream_2_V_full_n : IN STD_LOGIC;
    src0_data_stream_2_V_write : OUT STD_LOGIC;
    src1_data_stream_0_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    src1_data_stream_0_V_full_n : IN STD_LOGIC;
    src1_data_stream_0_V_write : OUT STD_LOGIC;
    src1_data_stream_1_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    src1_data_stream_1_V_full_n : IN STD_LOGIC;
    src1_data_stream_1_V_write : OUT STD_LOGIC;
    src1_data_stream_2_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    src1_data_stream_2_V_full_n : IN STD_LOGIC;
    src1_data_stream_2_V_write : OUT STD_LOGIC;
    ap_return_0 : OUT STD_LOGIC_VECTOR (11 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (11 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (11 downto 0);
    ap_return_3 : OUT STD_LOGIC_VECTOR (11 downto 0);
    ap_return_4 : OUT STD_LOGIC_VECTOR (11 downto 0);
    ap_return_5 : OUT STD_LOGIC_VECTOR (11 downto 0);
    ap_return_6 : OUT STD_LOGIC_VECTOR (11 downto 0);
    ap_return_7 : OUT STD_LOGIC_VECTOR (11 downto 0) );
end;


architecture behav of image_filter_Block_Mat_exit1220_proc1 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_st1_fsm_0 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_st2_fsm_1 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";

    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_sig_cseq_ST_st1_fsm_0 : STD_LOGIC;
    signal ap_sig_bdd_21 : BOOLEAN;
    signal ap_sig_bdd_82 : BOOLEAN;
    signal grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_ap_start : STD_LOGIC;
    signal grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_ap_done : STD_LOGIC;
    signal grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_ap_idle : STD_LOGIC;
    signal grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_ap_ready : STD_LOGIC;
    signal grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_src_rows_V_read : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_src_cols_V_read : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_src_data_stream_0_V_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_src_data_stream_0_V_empty_n : STD_LOGIC;
    signal grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_src_data_stream_0_V_read : STD_LOGIC;
    signal grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_src_data_stream_1_V_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_src_data_stream_1_V_empty_n : STD_LOGIC;
    signal grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_src_data_stream_1_V_read : STD_LOGIC;
    signal grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_src_data_stream_2_V_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_src_data_stream_2_V_empty_n : STD_LOGIC;
    signal grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_src_data_stream_2_V_read : STD_LOGIC;
    signal grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_dst1_rows_V_read : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_dst1_cols_V_read : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_dst1_data_stream_0_V_din : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_dst1_data_stream_0_V_full_n : STD_LOGIC;
    signal grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_dst1_data_stream_0_V_write : STD_LOGIC;
    signal grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_dst1_data_stream_1_V_din : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_dst1_data_stream_1_V_full_n : STD_LOGIC;
    signal grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_dst1_data_stream_1_V_write : STD_LOGIC;
    signal grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_dst1_data_stream_2_V_din : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_dst1_data_stream_2_V_full_n : STD_LOGIC;
    signal grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_dst1_data_stream_2_V_write : STD_LOGIC;
    signal grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_dst2_rows_V_read : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_dst2_cols_V_read : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_dst2_data_stream_0_V_din : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_dst2_data_stream_0_V_full_n : STD_LOGIC;
    signal grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_dst2_data_stream_0_V_write : STD_LOGIC;
    signal grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_dst2_data_stream_1_V_din : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_dst2_data_stream_1_V_full_n : STD_LOGIC;
    signal grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_dst2_data_stream_1_V_write : STD_LOGIC;
    signal grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_dst2_data_stream_2_V_din : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_dst2_data_stream_2_V_full_n : STD_LOGIC;
    signal grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_dst2_data_stream_2_V_write : STD_LOGIC;
    signal grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_ap_start_ap_start_reg : STD_LOGIC := '0';
    signal ap_sig_cseq_ST_st2_fsm_1 : STD_LOGIC;
    signal ap_sig_bdd_137 : BOOLEAN;
    signal ap_return_0_preg : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    signal ap_return_1_preg : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    signal ap_return_2_preg : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    signal ap_return_3_preg : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    signal ap_return_4_preg : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    signal ap_return_5_preg : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    signal ap_return_6_preg : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    signal ap_return_7_preg : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);

    component image_filter_Duplicate_1080_1920_32_32_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        src_rows_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        src_cols_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        src_data_stream_0_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        src_data_stream_0_V_empty_n : IN STD_LOGIC;
        src_data_stream_0_V_read : OUT STD_LOGIC;
        src_data_stream_1_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        src_data_stream_1_V_empty_n : IN STD_LOGIC;
        src_data_stream_1_V_read : OUT STD_LOGIC;
        src_data_stream_2_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        src_data_stream_2_V_empty_n : IN STD_LOGIC;
        src_data_stream_2_V_read : OUT STD_LOGIC;
        dst1_rows_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        dst1_cols_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        dst1_data_stream_0_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        dst1_data_stream_0_V_full_n : IN STD_LOGIC;
        dst1_data_stream_0_V_write : OUT STD_LOGIC;
        dst1_data_stream_1_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        dst1_data_stream_1_V_full_n : IN STD_LOGIC;
        dst1_data_stream_1_V_write : OUT STD_LOGIC;
        dst1_data_stream_2_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        dst1_data_stream_2_V_full_n : IN STD_LOGIC;
        dst1_data_stream_2_V_write : OUT STD_LOGIC;
        dst2_rows_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        dst2_cols_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        dst2_data_stream_0_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        dst2_data_stream_0_V_full_n : IN STD_LOGIC;
        dst2_data_stream_0_V_write : OUT STD_LOGIC;
        dst2_data_stream_1_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        dst2_data_stream_1_V_full_n : IN STD_LOGIC;
        dst2_data_stream_1_V_write : OUT STD_LOGIC;
        dst2_data_stream_2_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        dst2_data_stream_2_V_full_n : IN STD_LOGIC;
        dst2_data_stream_2_V_write : OUT STD_LOGIC );
    end component;



begin
    grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97 : component image_filter_Duplicate_1080_1920_32_32_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_ap_start,
        ap_done => grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_ap_done,
        ap_idle => grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_ap_idle,
        ap_ready => grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_ap_ready,
        src_rows_V_read => grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_src_rows_V_read,
        src_cols_V_read => grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_src_cols_V_read,
        src_data_stream_0_V_dout => grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_src_data_stream_0_V_dout,
        src_data_stream_0_V_empty_n => grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_src_data_stream_0_V_empty_n,
        src_data_stream_0_V_read => grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_src_data_stream_0_V_read,
        src_data_stream_1_V_dout => grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_src_data_stream_1_V_dout,
        src_data_stream_1_V_empty_n => grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_src_data_stream_1_V_empty_n,
        src_data_stream_1_V_read => grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_src_data_stream_1_V_read,
        src_data_stream_2_V_dout => grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_src_data_stream_2_V_dout,
        src_data_stream_2_V_empty_n => grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_src_data_stream_2_V_empty_n,
        src_data_stream_2_V_read => grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_src_data_stream_2_V_read,
        dst1_rows_V_read => grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_dst1_rows_V_read,
        dst1_cols_V_read => grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_dst1_cols_V_read,
        dst1_data_stream_0_V_din => grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_dst1_data_stream_0_V_din,
        dst1_data_stream_0_V_full_n => grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_dst1_data_stream_0_V_full_n,
        dst1_data_stream_0_V_write => grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_dst1_data_stream_0_V_write,
        dst1_data_stream_1_V_din => grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_dst1_data_stream_1_V_din,
        dst1_data_stream_1_V_full_n => grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_dst1_data_stream_1_V_full_n,
        dst1_data_stream_1_V_write => grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_dst1_data_stream_1_V_write,
        dst1_data_stream_2_V_din => grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_dst1_data_stream_2_V_din,
        dst1_data_stream_2_V_full_n => grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_dst1_data_stream_2_V_full_n,
        dst1_data_stream_2_V_write => grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_dst1_data_stream_2_V_write,
        dst2_rows_V_read => grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_dst2_rows_V_read,
        dst2_cols_V_read => grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_dst2_cols_V_read,
        dst2_data_stream_0_V_din => grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_dst2_data_stream_0_V_din,
        dst2_data_stream_0_V_full_n => grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_dst2_data_stream_0_V_full_n,
        dst2_data_stream_0_V_write => grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_dst2_data_stream_0_V_write,
        dst2_data_stream_1_V_din => grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_dst2_data_stream_1_V_din,
        dst2_data_stream_1_V_full_n => grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_dst2_data_stream_1_V_full_n,
        dst2_data_stream_1_V_write => grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_dst2_data_stream_1_V_write,
        dst2_data_stream_2_V_din => grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_dst2_data_stream_2_V_din,
        dst2_data_stream_2_V_full_n => grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_dst2_data_stream_2_V_full_n,
        dst2_data_stream_2_V_write => grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_dst2_data_stream_2_V_write);





    -- the current state (ap_CS_fsm) of the state machine. --
    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_st1_fsm_0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    -- ap_done_reg assign process. --
    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_continue)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1) and not((ap_const_logic_0 = grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_ap_done)))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    -- ap_return_0_preg assign process. --
    ap_return_0_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_0_preg <= ap_const_lv12_0;
            else
                if (((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1) and not((ap_const_logic_0 = grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_ap_done)))) then 
                    ap_return_0_preg <= p_read;
                end if; 
            end if;
        end if;
    end process;


    -- ap_return_1_preg assign process. --
    ap_return_1_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_1_preg <= ap_const_lv12_0;
            else
                if (((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1) and not((ap_const_logic_0 = grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_ap_done)))) then 
                    ap_return_1_preg <= p_read2;
                end if; 
            end if;
        end if;
    end process;


    -- ap_return_2_preg assign process. --
    ap_return_2_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_2_preg <= ap_const_lv12_0;
            else
                if (((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1) and not((ap_const_logic_0 = grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_ap_done)))) then 
                    ap_return_2_preg <= p_read;
                end if; 
            end if;
        end if;
    end process;


    -- ap_return_3_preg assign process. --
    ap_return_3_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_3_preg <= ap_const_lv12_0;
            else
                if (((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1) and not((ap_const_logic_0 = grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_ap_done)))) then 
                    ap_return_3_preg <= p_read2;
                end if; 
            end if;
        end if;
    end process;


    -- ap_return_4_preg assign process. --
    ap_return_4_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_4_preg <= ap_const_lv12_0;
            else
                if (((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1) and not((ap_const_logic_0 = grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_ap_done)))) then 
                    ap_return_4_preg <= p_read;
                end if; 
            end if;
        end if;
    end process;


    -- ap_return_5_preg assign process. --
    ap_return_5_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_5_preg <= ap_const_lv12_0;
            else
                if (((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1) and not((ap_const_logic_0 = grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_ap_done)))) then 
                    ap_return_5_preg <= p_read2;
                end if; 
            end if;
        end if;
    end process;


    -- ap_return_6_preg assign process. --
    ap_return_6_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_6_preg <= ap_const_lv12_0;
            else
                if (((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1) and not((ap_const_logic_0 = grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_ap_done)))) then 
                    ap_return_6_preg <= p_read;
                end if; 
            end if;
        end if;
    end process;


    -- ap_return_7_preg assign process. --
    ap_return_7_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_7_preg <= ap_const_lv12_0;
            else
                if (((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1) and not((ap_const_logic_0 = grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_ap_done)))) then 
                    ap_return_7_preg <= p_read2;
                end if; 
            end if;
        end if;
    end process;


    -- grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_ap_start_ap_start_reg assign process. --
    grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_ap_start_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_ap_start_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and not(ap_sig_bdd_82))) then 
                    grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_ap_start_ap_start_reg <= ap_const_logic_1;
                elsif ((ap_const_logic_1 = grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_ap_ready)) then 
                    grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_ap_start_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    -- the next state (ap_NS_fsm) of the state machine. --
    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_sig_bdd_82, grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_ap_done)
    begin
        case ap_CS_fsm is
            when ap_ST_st1_fsm_0 => 
                if (not(ap_sig_bdd_82)) then
                    ap_NS_fsm <= ap_ST_st2_fsm_1;
                else
                    ap_NS_fsm <= ap_ST_st1_fsm_0;
                end if;
            when ap_ST_st2_fsm_1 => 
                if (not((ap_const_logic_0 = grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_ap_done))) then
                    ap_NS_fsm <= ap_ST_st1_fsm_0;
                else
                    ap_NS_fsm <= ap_ST_st2_fsm_1;
                end if;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;

    -- ap_done assign process. --
    ap_done_assign_proc : process(ap_done_reg, grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_ap_done, ap_sig_cseq_ST_st2_fsm_1)
    begin
        if (((ap_const_logic_1 = ap_done_reg) or ((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1) and not((ap_const_logic_0 = grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_ap_done))))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    -- ap_idle assign process. --
    ap_idle_assign_proc : process(ap_start, ap_sig_cseq_ST_st1_fsm_0)
    begin
        if ((not((ap_const_logic_1 = ap_start)) and (ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    -- ap_ready assign process. --
    ap_ready_assign_proc : process(grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_ap_done, ap_sig_cseq_ST_st2_fsm_1)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1) and not((ap_const_logic_0 = grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_ap_done)))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    -- ap_return_0 assign process. --
    ap_return_0_assign_proc : process(p_read, grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_ap_done, ap_sig_cseq_ST_st2_fsm_1, ap_return_0_preg)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1) and not((ap_const_logic_0 = grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_ap_done)))) then 
            ap_return_0 <= p_read;
        else 
            ap_return_0 <= ap_return_0_preg;
        end if; 
    end process;


    -- ap_return_1 assign process. --
    ap_return_1_assign_proc : process(p_read2, grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_ap_done, ap_sig_cseq_ST_st2_fsm_1, ap_return_1_preg)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1) and not((ap_const_logic_0 = grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_ap_done)))) then 
            ap_return_1 <= p_read2;
        else 
            ap_return_1 <= ap_return_1_preg;
        end if; 
    end process;


    -- ap_return_2 assign process. --
    ap_return_2_assign_proc : process(p_read, grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_ap_done, ap_sig_cseq_ST_st2_fsm_1, ap_return_2_preg)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1) and not((ap_const_logic_0 = grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_ap_done)))) then 
            ap_return_2 <= p_read;
        else 
            ap_return_2 <= ap_return_2_preg;
        end if; 
    end process;


    -- ap_return_3 assign process. --
    ap_return_3_assign_proc : process(p_read2, grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_ap_done, ap_sig_cseq_ST_st2_fsm_1, ap_return_3_preg)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1) and not((ap_const_logic_0 = grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_ap_done)))) then 
            ap_return_3 <= p_read2;
        else 
            ap_return_3 <= ap_return_3_preg;
        end if; 
    end process;


    -- ap_return_4 assign process. --
    ap_return_4_assign_proc : process(p_read, grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_ap_done, ap_sig_cseq_ST_st2_fsm_1, ap_return_4_preg)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1) and not((ap_const_logic_0 = grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_ap_done)))) then 
            ap_return_4 <= p_read;
        else 
            ap_return_4 <= ap_return_4_preg;
        end if; 
    end process;


    -- ap_return_5 assign process. --
    ap_return_5_assign_proc : process(p_read2, grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_ap_done, ap_sig_cseq_ST_st2_fsm_1, ap_return_5_preg)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1) and not((ap_const_logic_0 = grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_ap_done)))) then 
            ap_return_5 <= p_read2;
        else 
            ap_return_5 <= ap_return_5_preg;
        end if; 
    end process;


    -- ap_return_6 assign process. --
    ap_return_6_assign_proc : process(p_read, grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_ap_done, ap_sig_cseq_ST_st2_fsm_1, ap_return_6_preg)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1) and not((ap_const_logic_0 = grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_ap_done)))) then 
            ap_return_6 <= p_read;
        else 
            ap_return_6 <= ap_return_6_preg;
        end if; 
    end process;


    -- ap_return_7 assign process. --
    ap_return_7_assign_proc : process(p_read2, grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_ap_done, ap_sig_cseq_ST_st2_fsm_1, ap_return_7_preg)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1) and not((ap_const_logic_0 = grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_ap_done)))) then 
            ap_return_7 <= p_read2;
        else 
            ap_return_7 <= ap_return_7_preg;
        end if; 
    end process;


    -- ap_sig_bdd_137 assign process. --
    ap_sig_bdd_137_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_bdd_137 <= (ap_const_lv1_1 = ap_CS_fsm(1 downto 1));
    end process;


    -- ap_sig_bdd_21 assign process. --
    ap_sig_bdd_21_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_bdd_21 <= (ap_CS_fsm(0 downto 0) = ap_const_lv1_1);
    end process;


    -- ap_sig_bdd_82 assign process. --
    ap_sig_bdd_82_assign_proc : process(ap_start, ap_done_reg)
    begin
                ap_sig_bdd_82 <= ((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    -- ap_sig_cseq_ST_st1_fsm_0 assign process. --
    ap_sig_cseq_ST_st1_fsm_0_assign_proc : process(ap_sig_bdd_21)
    begin
        if (ap_sig_bdd_21) then 
            ap_sig_cseq_ST_st1_fsm_0 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st1_fsm_0 <= ap_const_logic_0;
        end if; 
    end process;


    -- ap_sig_cseq_ST_st2_fsm_1 assign process. --
    ap_sig_cseq_ST_st2_fsm_1_assign_proc : process(ap_sig_bdd_137)
    begin
        if (ap_sig_bdd_137) then 
            ap_sig_cseq_ST_st2_fsm_1 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st2_fsm_1 <= ap_const_logic_0;
        end if; 
    end process;

    grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_ap_start <= grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_ap_start_ap_start_reg;
    grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_dst1_cols_V_read <= p_read2;
    grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_dst1_data_stream_0_V_full_n <= src0_data_stream_0_V_full_n;
    grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_dst1_data_stream_1_V_full_n <= src0_data_stream_1_V_full_n;
    grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_dst1_data_stream_2_V_full_n <= src0_data_stream_2_V_full_n;
    grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_dst1_rows_V_read <= p_read;
    grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_dst2_cols_V_read <= p_read2;
    grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_dst2_data_stream_0_V_full_n <= src1_data_stream_0_V_full_n;
    grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_dst2_data_stream_1_V_full_n <= src1_data_stream_1_V_full_n;
    grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_dst2_data_stream_2_V_full_n <= src1_data_stream_2_V_full_n;
    grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_dst2_rows_V_read <= p_read;
    grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_src_cols_V_read <= p_read17;
    grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_src_data_stream_0_V_dout <= p_src_data_stream_0_V_dout;
    grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_src_data_stream_0_V_empty_n <= p_src_data_stream_0_V_empty_n;
    grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_src_data_stream_1_V_dout <= p_src_data_stream_1_V_dout;
    grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_src_data_stream_1_V_empty_n <= p_src_data_stream_1_V_empty_n;
    grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_src_data_stream_2_V_dout <= p_src_data_stream_2_V_dout;
    grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_src_data_stream_2_V_empty_n <= p_src_data_stream_2_V_empty_n;
    grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_src_rows_V_read <= p_read16;

    -- p_src_data_stream_0_V_read assign process. --
    p_src_data_stream_0_V_read_assign_proc : process(ap_sig_cseq_ST_st1_fsm_0, grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_src_data_stream_0_V_read, ap_sig_cseq_ST_st2_fsm_1)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) or (ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1))) then 
            p_src_data_stream_0_V_read <= grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_src_data_stream_0_V_read;
        else 
            p_src_data_stream_0_V_read <= ap_const_logic_0;
        end if; 
    end process;


    -- p_src_data_stream_1_V_read assign process. --
    p_src_data_stream_1_V_read_assign_proc : process(ap_sig_cseq_ST_st1_fsm_0, grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_src_data_stream_1_V_read, ap_sig_cseq_ST_st2_fsm_1)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) or (ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1))) then 
            p_src_data_stream_1_V_read <= grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_src_data_stream_1_V_read;
        else 
            p_src_data_stream_1_V_read <= ap_const_logic_0;
        end if; 
    end process;


    -- p_src_data_stream_2_V_read assign process. --
    p_src_data_stream_2_V_read_assign_proc : process(ap_sig_cseq_ST_st1_fsm_0, grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_src_data_stream_2_V_read, ap_sig_cseq_ST_st2_fsm_1)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) or (ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1))) then 
            p_src_data_stream_2_V_read <= grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_src_data_stream_2_V_read;
        else 
            p_src_data_stream_2_V_read <= ap_const_logic_0;
        end if; 
    end process;

    src0_data_stream_0_V_din <= grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_dst1_data_stream_0_V_din;

    -- src0_data_stream_0_V_write assign process. --
    src0_data_stream_0_V_write_assign_proc : process(ap_sig_cseq_ST_st1_fsm_0, grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_dst1_data_stream_0_V_write, ap_sig_cseq_ST_st2_fsm_1)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) or (ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1))) then 
            src0_data_stream_0_V_write <= grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_dst1_data_stream_0_V_write;
        else 
            src0_data_stream_0_V_write <= ap_const_logic_0;
        end if; 
    end process;

    src0_data_stream_1_V_din <= grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_dst1_data_stream_1_V_din;

    -- src0_data_stream_1_V_write assign process. --
    src0_data_stream_1_V_write_assign_proc : process(ap_sig_cseq_ST_st1_fsm_0, grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_dst1_data_stream_1_V_write, ap_sig_cseq_ST_st2_fsm_1)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) or (ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1))) then 
            src0_data_stream_1_V_write <= grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_dst1_data_stream_1_V_write;
        else 
            src0_data_stream_1_V_write <= ap_const_logic_0;
        end if; 
    end process;

    src0_data_stream_2_V_din <= grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_dst1_data_stream_2_V_din;

    -- src0_data_stream_2_V_write assign process. --
    src0_data_stream_2_V_write_assign_proc : process(ap_sig_cseq_ST_st1_fsm_0, grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_dst1_data_stream_2_V_write, ap_sig_cseq_ST_st2_fsm_1)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) or (ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1))) then 
            src0_data_stream_2_V_write <= grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_dst1_data_stream_2_V_write;
        else 
            src0_data_stream_2_V_write <= ap_const_logic_0;
        end if; 
    end process;

    src1_data_stream_0_V_din <= grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_dst2_data_stream_0_V_din;

    -- src1_data_stream_0_V_write assign process. --
    src1_data_stream_0_V_write_assign_proc : process(ap_sig_cseq_ST_st1_fsm_0, grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_dst2_data_stream_0_V_write, ap_sig_cseq_ST_st2_fsm_1)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) or (ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1))) then 
            src1_data_stream_0_V_write <= grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_dst2_data_stream_0_V_write;
        else 
            src1_data_stream_0_V_write <= ap_const_logic_0;
        end if; 
    end process;

    src1_data_stream_1_V_din <= grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_dst2_data_stream_1_V_din;

    -- src1_data_stream_1_V_write assign process. --
    src1_data_stream_1_V_write_assign_proc : process(ap_sig_cseq_ST_st1_fsm_0, grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_dst2_data_stream_1_V_write, ap_sig_cseq_ST_st2_fsm_1)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) or (ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1))) then 
            src1_data_stream_1_V_write <= grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_dst2_data_stream_1_V_write;
        else 
            src1_data_stream_1_V_write <= ap_const_logic_0;
        end if; 
    end process;

    src1_data_stream_2_V_din <= grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_dst2_data_stream_2_V_din;

    -- src1_data_stream_2_V_write assign process. --
    src1_data_stream_2_V_write_assign_proc : process(ap_sig_cseq_ST_st1_fsm_0, grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_dst2_data_stream_2_V_write, ap_sig_cseq_ST_st2_fsm_1)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) or (ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1))) then 
            src1_data_stream_2_V_write <= grp_image_filter_Duplicate_1080_1920_32_32_s_fu_97_dst2_data_stream_2_V_write;
        else 
            src1_data_stream_2_V_write <= ap_const_logic_0;
        end if; 
    end process;

end behav;
