// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.4
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#1 "/home/alok/githum/Zedboard/learning/training/my/adder/hls/adder/solution1/adder.cpp"
#1 "<built-in>"
#1 "<command-line>"
#1 "/home/alok/githum/Zedboard/learning/training/my/adder/hls/adder/solution1/adder.cpp"



#ifndef HLS_FASTSIM
#include "apatb_adder.h"
#endif
#define adder(...) AESL_ORIG_DUT_adder(__VA_ARGS__)
#3 "/home/alok/githum/Zedboard/learning/training/my/adder/hls/adder/solution1/adder.cpp"
void adder(int *a,int *b,int *c) {
#pragma HLS INTERFACE s_axilite port=return bundle=AXI_CTRL
#pragma HLS INTERFACE s_axilite port=c bundle=AXI_CTRL
#pragma HLS INTERFACE s_axilite port=b bundle=AXI_CTRL
#pragma HLS INTERFACE s_axilite port=a bundle=AXI_CTRL

 *c=*a+*b;

}
#undef adder

#11 "/home/alok/githum/Zedboard/learning/training/my/adder/hls/adder/solution1/adder.cpp"
