// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.4
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#include "image_filter_Block_Mat_exit1222_proc1.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic image_filter_Block_Mat_exit1222_proc1::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic image_filter_Block_Mat_exit1222_proc1::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<2> image_filter_Block_Mat_exit1222_proc1::ap_ST_st1_fsm_0 = "1";
const sc_lv<2> image_filter_Block_Mat_exit1222_proc1::ap_ST_st2_fsm_1 = "10";
const sc_lv<32> image_filter_Block_Mat_exit1222_proc1::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> image_filter_Block_Mat_exit1222_proc1::ap_const_lv1_1 = "1";
const sc_lv<32> image_filter_Block_Mat_exit1222_proc1::ap_const_lv32_1 = "1";
const sc_lv<12> image_filter_Block_Mat_exit1222_proc1::ap_const_lv12_0 = "000000000000";

image_filter_Block_Mat_exit1222_proc1::image_filter_Block_Mat_exit1222_proc1(sc_module_name name) : sc_module(name), mVcdFile(0) {
    grp_image_filter_CvtColor_fu_67 = new image_filter_CvtColor("grp_image_filter_CvtColor_fu_67");
    grp_image_filter_CvtColor_fu_67->ap_clk(ap_clk);
    grp_image_filter_CvtColor_fu_67->ap_rst(ap_rst);
    grp_image_filter_CvtColor_fu_67->ap_start(grp_image_filter_CvtColor_fu_67_ap_start);
    grp_image_filter_CvtColor_fu_67->ap_done(grp_image_filter_CvtColor_fu_67_ap_done);
    grp_image_filter_CvtColor_fu_67->ap_idle(grp_image_filter_CvtColor_fu_67_ap_idle);
    grp_image_filter_CvtColor_fu_67->ap_ready(grp_image_filter_CvtColor_fu_67_ap_ready);
    grp_image_filter_CvtColor_fu_67->p_src_rows_V_read(grp_image_filter_CvtColor_fu_67_p_src_rows_V_read);
    grp_image_filter_CvtColor_fu_67->p_src_cols_V_read(grp_image_filter_CvtColor_fu_67_p_src_cols_V_read);
    grp_image_filter_CvtColor_fu_67->p_src_data_stream_0_V_dout(grp_image_filter_CvtColor_fu_67_p_src_data_stream_0_V_dout);
    grp_image_filter_CvtColor_fu_67->p_src_data_stream_0_V_empty_n(grp_image_filter_CvtColor_fu_67_p_src_data_stream_0_V_empty_n);
    grp_image_filter_CvtColor_fu_67->p_src_data_stream_0_V_read(grp_image_filter_CvtColor_fu_67_p_src_data_stream_0_V_read);
    grp_image_filter_CvtColor_fu_67->p_src_data_stream_1_V_dout(grp_image_filter_CvtColor_fu_67_p_src_data_stream_1_V_dout);
    grp_image_filter_CvtColor_fu_67->p_src_data_stream_1_V_empty_n(grp_image_filter_CvtColor_fu_67_p_src_data_stream_1_V_empty_n);
    grp_image_filter_CvtColor_fu_67->p_src_data_stream_1_V_read(grp_image_filter_CvtColor_fu_67_p_src_data_stream_1_V_read);
    grp_image_filter_CvtColor_fu_67->p_src_data_stream_2_V_dout(grp_image_filter_CvtColor_fu_67_p_src_data_stream_2_V_dout);
    grp_image_filter_CvtColor_fu_67->p_src_data_stream_2_V_empty_n(grp_image_filter_CvtColor_fu_67_p_src_data_stream_2_V_empty_n);
    grp_image_filter_CvtColor_fu_67->p_src_data_stream_2_V_read(grp_image_filter_CvtColor_fu_67_p_src_data_stream_2_V_read);
    grp_image_filter_CvtColor_fu_67->p_dst_data_stream_V_din(grp_image_filter_CvtColor_fu_67_p_dst_data_stream_V_din);
    grp_image_filter_CvtColor_fu_67->p_dst_data_stream_V_full_n(grp_image_filter_CvtColor_fu_67_p_dst_data_stream_V_full_n);
    grp_image_filter_CvtColor_fu_67->p_dst_data_stream_V_write(grp_image_filter_CvtColor_fu_67_p_dst_data_stream_V_write);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( grp_image_filter_CvtColor_fu_67_ap_done );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( grp_image_filter_CvtColor_fu_67_ap_done );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_ap_return_0);
    sensitive << ( p_read );
    sensitive << ( grp_image_filter_CvtColor_fu_67_ap_done );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( ap_return_0_preg );

    SC_METHOD(thread_ap_return_1);
    sensitive << ( p_read2 );
    sensitive << ( grp_image_filter_CvtColor_fu_67_ap_done );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( ap_return_1_preg );

    SC_METHOD(thread_ap_sig_bdd_21);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_56);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_sig_bdd_88);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_cseq_ST_st1_fsm_0);
    sensitive << ( ap_sig_bdd_21 );

    SC_METHOD(thread_ap_sig_cseq_ST_st2_fsm_1);
    sensitive << ( ap_sig_bdd_88 );

    SC_METHOD(thread_gray_data_stream_0_V_din);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( grp_image_filter_CvtColor_fu_67_p_dst_data_stream_V_din );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_gray_data_stream_0_V_write);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( grp_image_filter_CvtColor_fu_67_p_dst_data_stream_V_write );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_grp_image_filter_CvtColor_fu_67_ap_start);
    sensitive << ( grp_image_filter_CvtColor_fu_67_ap_start_ap_start_reg );

    SC_METHOD(thread_grp_image_filter_CvtColor_fu_67_p_dst_data_stream_V_full_n);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( gray_data_stream_0_V_full_n );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_grp_image_filter_CvtColor_fu_67_p_src_cols_V_read);
    sensitive << ( p_read7 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_grp_image_filter_CvtColor_fu_67_p_src_data_stream_0_V_dout);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( src0_data_stream_0_V_dout );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_grp_image_filter_CvtColor_fu_67_p_src_data_stream_0_V_empty_n);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( src0_data_stream_0_V_empty_n );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_grp_image_filter_CvtColor_fu_67_p_src_data_stream_1_V_dout);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( src0_data_stream_1_V_dout );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_grp_image_filter_CvtColor_fu_67_p_src_data_stream_1_V_empty_n);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( src0_data_stream_1_V_empty_n );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_grp_image_filter_CvtColor_fu_67_p_src_data_stream_2_V_dout);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( src0_data_stream_2_V_dout );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_grp_image_filter_CvtColor_fu_67_p_src_data_stream_2_V_empty_n);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( src0_data_stream_2_V_empty_n );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_grp_image_filter_CvtColor_fu_67_p_src_rows_V_read);
    sensitive << ( p_read6 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_src0_data_stream_0_V_read);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( grp_image_filter_CvtColor_fu_67_p_src_data_stream_0_V_read );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_src0_data_stream_1_V_read);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( grp_image_filter_CvtColor_fu_67_p_src_data_stream_1_V_read );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_src0_data_stream_2_V_read);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( grp_image_filter_CvtColor_fu_67_p_src_data_stream_2_V_read );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_sig_bdd_56 );
    sensitive << ( grp_image_filter_CvtColor_fu_67_ap_done );

    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "01";
    grp_image_filter_CvtColor_fu_67_ap_start_ap_start_reg = SC_LOGIC_0;
    ap_return_0_preg = "000000000000";
    ap_return_1_preg = "000000000000";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "image_filter_Block_Mat_exit1222_proc1_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, p_read, "(port)p_read");
    sc_trace(mVcdFile, p_read2, "(port)p_read2");
    sc_trace(mVcdFile, p_read6, "(port)p_read6");
    sc_trace(mVcdFile, p_read7, "(port)p_read7");
    sc_trace(mVcdFile, src0_data_stream_0_V_dout, "(port)src0_data_stream_0_V_dout");
    sc_trace(mVcdFile, src0_data_stream_0_V_empty_n, "(port)src0_data_stream_0_V_empty_n");
    sc_trace(mVcdFile, src0_data_stream_0_V_read, "(port)src0_data_stream_0_V_read");
    sc_trace(mVcdFile, src0_data_stream_1_V_dout, "(port)src0_data_stream_1_V_dout");
    sc_trace(mVcdFile, src0_data_stream_1_V_empty_n, "(port)src0_data_stream_1_V_empty_n");
    sc_trace(mVcdFile, src0_data_stream_1_V_read, "(port)src0_data_stream_1_V_read");
    sc_trace(mVcdFile, src0_data_stream_2_V_dout, "(port)src0_data_stream_2_V_dout");
    sc_trace(mVcdFile, src0_data_stream_2_V_empty_n, "(port)src0_data_stream_2_V_empty_n");
    sc_trace(mVcdFile, src0_data_stream_2_V_read, "(port)src0_data_stream_2_V_read");
    sc_trace(mVcdFile, gray_data_stream_0_V_din, "(port)gray_data_stream_0_V_din");
    sc_trace(mVcdFile, gray_data_stream_0_V_full_n, "(port)gray_data_stream_0_V_full_n");
    sc_trace(mVcdFile, gray_data_stream_0_V_write, "(port)gray_data_stream_0_V_write");
    sc_trace(mVcdFile, ap_return_0, "(port)ap_return_0");
    sc_trace(mVcdFile, ap_return_1, "(port)ap_return_1");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st1_fsm_0, "ap_sig_cseq_ST_st1_fsm_0");
    sc_trace(mVcdFile, ap_sig_bdd_21, "ap_sig_bdd_21");
    sc_trace(mVcdFile, ap_sig_bdd_56, "ap_sig_bdd_56");
    sc_trace(mVcdFile, grp_image_filter_CvtColor_fu_67_ap_start, "grp_image_filter_CvtColor_fu_67_ap_start");
    sc_trace(mVcdFile, grp_image_filter_CvtColor_fu_67_ap_done, "grp_image_filter_CvtColor_fu_67_ap_done");
    sc_trace(mVcdFile, grp_image_filter_CvtColor_fu_67_ap_idle, "grp_image_filter_CvtColor_fu_67_ap_idle");
    sc_trace(mVcdFile, grp_image_filter_CvtColor_fu_67_ap_ready, "grp_image_filter_CvtColor_fu_67_ap_ready");
    sc_trace(mVcdFile, grp_image_filter_CvtColor_fu_67_p_src_rows_V_read, "grp_image_filter_CvtColor_fu_67_p_src_rows_V_read");
    sc_trace(mVcdFile, grp_image_filter_CvtColor_fu_67_p_src_cols_V_read, "grp_image_filter_CvtColor_fu_67_p_src_cols_V_read");
    sc_trace(mVcdFile, grp_image_filter_CvtColor_fu_67_p_src_data_stream_0_V_dout, "grp_image_filter_CvtColor_fu_67_p_src_data_stream_0_V_dout");
    sc_trace(mVcdFile, grp_image_filter_CvtColor_fu_67_p_src_data_stream_0_V_empty_n, "grp_image_filter_CvtColor_fu_67_p_src_data_stream_0_V_empty_n");
    sc_trace(mVcdFile, grp_image_filter_CvtColor_fu_67_p_src_data_stream_0_V_read, "grp_image_filter_CvtColor_fu_67_p_src_data_stream_0_V_read");
    sc_trace(mVcdFile, grp_image_filter_CvtColor_fu_67_p_src_data_stream_1_V_dout, "grp_image_filter_CvtColor_fu_67_p_src_data_stream_1_V_dout");
    sc_trace(mVcdFile, grp_image_filter_CvtColor_fu_67_p_src_data_stream_1_V_empty_n, "grp_image_filter_CvtColor_fu_67_p_src_data_stream_1_V_empty_n");
    sc_trace(mVcdFile, grp_image_filter_CvtColor_fu_67_p_src_data_stream_1_V_read, "grp_image_filter_CvtColor_fu_67_p_src_data_stream_1_V_read");
    sc_trace(mVcdFile, grp_image_filter_CvtColor_fu_67_p_src_data_stream_2_V_dout, "grp_image_filter_CvtColor_fu_67_p_src_data_stream_2_V_dout");
    sc_trace(mVcdFile, grp_image_filter_CvtColor_fu_67_p_src_data_stream_2_V_empty_n, "grp_image_filter_CvtColor_fu_67_p_src_data_stream_2_V_empty_n");
    sc_trace(mVcdFile, grp_image_filter_CvtColor_fu_67_p_src_data_stream_2_V_read, "grp_image_filter_CvtColor_fu_67_p_src_data_stream_2_V_read");
    sc_trace(mVcdFile, grp_image_filter_CvtColor_fu_67_p_dst_data_stream_V_din, "grp_image_filter_CvtColor_fu_67_p_dst_data_stream_V_din");
    sc_trace(mVcdFile, grp_image_filter_CvtColor_fu_67_p_dst_data_stream_V_full_n, "grp_image_filter_CvtColor_fu_67_p_dst_data_stream_V_full_n");
    sc_trace(mVcdFile, grp_image_filter_CvtColor_fu_67_p_dst_data_stream_V_write, "grp_image_filter_CvtColor_fu_67_p_dst_data_stream_V_write");
    sc_trace(mVcdFile, grp_image_filter_CvtColor_fu_67_ap_start_ap_start_reg, "grp_image_filter_CvtColor_fu_67_ap_start_ap_start_reg");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st2_fsm_1, "ap_sig_cseq_ST_st2_fsm_1");
    sc_trace(mVcdFile, ap_sig_bdd_88, "ap_sig_bdd_88");
    sc_trace(mVcdFile, ap_return_0_preg, "ap_return_0_preg");
    sc_trace(mVcdFile, ap_return_1_preg, "ap_return_1_preg");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

image_filter_Block_Mat_exit1222_proc1::~image_filter_Block_Mat_exit1222_proc1() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete grp_image_filter_CvtColor_fu_67;
}

void image_filter_Block_Mat_exit1222_proc1::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_st1_fsm_0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
                    !esl_seteq<1,1,1>(ap_const_logic_0, grp_image_filter_CvtColor_fu_67_ap_done.read()))) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_0_preg = ap_const_lv12_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
             !esl_seteq<1,1,1>(ap_const_logic_0, grp_image_filter_CvtColor_fu_67_ap_done.read()))) {
            ap_return_0_preg = p_read.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_1_preg = ap_const_lv12_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
             !esl_seteq<1,1,1>(ap_const_logic_0, grp_image_filter_CvtColor_fu_67_ap_done.read()))) {
            ap_return_1_preg = p_read2.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_image_filter_CvtColor_fu_67_ap_start_ap_start_reg = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
             !ap_sig_bdd_56.read())) {
            grp_image_filter_CvtColor_fu_67_ap_start_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_image_filter_CvtColor_fu_67_ap_ready.read())) {
            grp_image_filter_CvtColor_fu_67_ap_start_ap_start_reg = ap_const_logic_0;
        }
    }
}

void image_filter_Block_Mat_exit1222_proc1::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_done_reg.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
          !esl_seteq<1,1,1>(ap_const_logic_0, grp_image_filter_CvtColor_fu_67_ap_done.read())))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void image_filter_Block_Mat_exit1222_proc1::thread_ap_idle() {
    if ((!esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void image_filter_Block_Mat_exit1222_proc1::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
         !esl_seteq<1,1,1>(ap_const_logic_0, grp_image_filter_CvtColor_fu_67_ap_done.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void image_filter_Block_Mat_exit1222_proc1::thread_ap_return_0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
         !esl_seteq<1,1,1>(ap_const_logic_0, grp_image_filter_CvtColor_fu_67_ap_done.read()))) {
        ap_return_0 = p_read.read();
    } else {
        ap_return_0 = ap_return_0_preg.read();
    }
}

void image_filter_Block_Mat_exit1222_proc1::thread_ap_return_1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
         !esl_seteq<1,1,1>(ap_const_logic_0, grp_image_filter_CvtColor_fu_67_ap_done.read()))) {
        ap_return_1 = p_read2.read();
    } else {
        ap_return_1 = ap_return_1_preg.read();
    }
}

void image_filter_Block_Mat_exit1222_proc1::thread_ap_sig_bdd_21() {
    ap_sig_bdd_21 = esl_seteq<1,1,1>(ap_CS_fsm.read().range(0, 0), ap_const_lv1_1);
}

void image_filter_Block_Mat_exit1222_proc1::thread_ap_sig_bdd_56() {
    ap_sig_bdd_56 = (esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void image_filter_Block_Mat_exit1222_proc1::thread_ap_sig_bdd_88() {
    ap_sig_bdd_88 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(1, 1));
}

void image_filter_Block_Mat_exit1222_proc1::thread_ap_sig_cseq_ST_st1_fsm_0() {
    if (ap_sig_bdd_21.read()) {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    }
}

void image_filter_Block_Mat_exit1222_proc1::thread_ap_sig_cseq_ST_st2_fsm_1() {
    if (ap_sig_bdd_88.read()) {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    }
}

void image_filter_Block_Mat_exit1222_proc1::thread_gray_data_stream_0_V_din() {
    gray_data_stream_0_V_din = grp_image_filter_CvtColor_fu_67_p_dst_data_stream_V_din.read();
}

void image_filter_Block_Mat_exit1222_proc1::thread_gray_data_stream_0_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()))) {
        gray_data_stream_0_V_write = grp_image_filter_CvtColor_fu_67_p_dst_data_stream_V_write.read();
    } else {
        gray_data_stream_0_V_write = ap_const_logic_0;
    }
}

void image_filter_Block_Mat_exit1222_proc1::thread_grp_image_filter_CvtColor_fu_67_ap_start() {
    grp_image_filter_CvtColor_fu_67_ap_start = grp_image_filter_CvtColor_fu_67_ap_start_ap_start_reg.read();
}

void image_filter_Block_Mat_exit1222_proc1::thread_grp_image_filter_CvtColor_fu_67_p_dst_data_stream_V_full_n() {
    grp_image_filter_CvtColor_fu_67_p_dst_data_stream_V_full_n = gray_data_stream_0_V_full_n.read();
}

void image_filter_Block_Mat_exit1222_proc1::thread_grp_image_filter_CvtColor_fu_67_p_src_cols_V_read() {
    grp_image_filter_CvtColor_fu_67_p_src_cols_V_read = p_read7.read();
}

void image_filter_Block_Mat_exit1222_proc1::thread_grp_image_filter_CvtColor_fu_67_p_src_data_stream_0_V_dout() {
    grp_image_filter_CvtColor_fu_67_p_src_data_stream_0_V_dout = src0_data_stream_0_V_dout.read();
}

void image_filter_Block_Mat_exit1222_proc1::thread_grp_image_filter_CvtColor_fu_67_p_src_data_stream_0_V_empty_n() {
    grp_image_filter_CvtColor_fu_67_p_src_data_stream_0_V_empty_n = src0_data_stream_0_V_empty_n.read();
}

void image_filter_Block_Mat_exit1222_proc1::thread_grp_image_filter_CvtColor_fu_67_p_src_data_stream_1_V_dout() {
    grp_image_filter_CvtColor_fu_67_p_src_data_stream_1_V_dout = src0_data_stream_1_V_dout.read();
}

void image_filter_Block_Mat_exit1222_proc1::thread_grp_image_filter_CvtColor_fu_67_p_src_data_stream_1_V_empty_n() {
    grp_image_filter_CvtColor_fu_67_p_src_data_stream_1_V_empty_n = src0_data_stream_1_V_empty_n.read();
}

void image_filter_Block_Mat_exit1222_proc1::thread_grp_image_filter_CvtColor_fu_67_p_src_data_stream_2_V_dout() {
    grp_image_filter_CvtColor_fu_67_p_src_data_stream_2_V_dout = src0_data_stream_2_V_dout.read();
}

void image_filter_Block_Mat_exit1222_proc1::thread_grp_image_filter_CvtColor_fu_67_p_src_data_stream_2_V_empty_n() {
    grp_image_filter_CvtColor_fu_67_p_src_data_stream_2_V_empty_n = src0_data_stream_2_V_empty_n.read();
}

void image_filter_Block_Mat_exit1222_proc1::thread_grp_image_filter_CvtColor_fu_67_p_src_rows_V_read() {
    grp_image_filter_CvtColor_fu_67_p_src_rows_V_read = p_read6.read();
}

void image_filter_Block_Mat_exit1222_proc1::thread_src0_data_stream_0_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()))) {
        src0_data_stream_0_V_read = grp_image_filter_CvtColor_fu_67_p_src_data_stream_0_V_read.read();
    } else {
        src0_data_stream_0_V_read = ap_const_logic_0;
    }
}

void image_filter_Block_Mat_exit1222_proc1::thread_src0_data_stream_1_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()))) {
        src0_data_stream_1_V_read = grp_image_filter_CvtColor_fu_67_p_src_data_stream_1_V_read.read();
    } else {
        src0_data_stream_1_V_read = ap_const_logic_0;
    }
}

void image_filter_Block_Mat_exit1222_proc1::thread_src0_data_stream_2_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()))) {
        src0_data_stream_2_V_read = grp_image_filter_CvtColor_fu_67_p_src_data_stream_2_V_read.read();
    } else {
        src0_data_stream_2_V_read = ap_const_logic_0;
    }
}

void image_filter_Block_Mat_exit1222_proc1::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if (!ap_sig_bdd_56.read()) {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            }
            break;
        case 2 : 
            if (!esl_seteq<1,1,1>(ap_const_logic_0, grp_image_filter_CvtColor_fu_67_ap_done.read())) {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            } else {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            }
            break;
        default : 
            ap_NS_fsm = "XX";
            break;
    }
}

}

