// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.4
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#ifndef _adder_HH_
#define _adder_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "adder_AXI_CTRL_s_axi.h"

namespace ap_rtl {

template<unsigned int C_S_AXI_AXI_CTRL_ADDR_WIDTH = 6,
         unsigned int C_S_AXI_AXI_CTRL_DATA_WIDTH = 32>
struct adder : public sc_module {
    // Port declarations 20
    sc_in< sc_logic > s_axi_AXI_CTRL_AWVALID;
    sc_out< sc_logic > s_axi_AXI_CTRL_AWREADY;
    sc_in< sc_uint<C_S_AXI_AXI_CTRL_ADDR_WIDTH> > s_axi_AXI_CTRL_AWADDR;
    sc_in< sc_logic > s_axi_AXI_CTRL_WVALID;
    sc_out< sc_logic > s_axi_AXI_CTRL_WREADY;
    sc_in< sc_uint<C_S_AXI_AXI_CTRL_DATA_WIDTH> > s_axi_AXI_CTRL_WDATA;
    sc_in< sc_uint<C_S_AXI_AXI_CTRL_DATA_WIDTH/8> > s_axi_AXI_CTRL_WSTRB;
    sc_in< sc_logic > s_axi_AXI_CTRL_ARVALID;
    sc_out< sc_logic > s_axi_AXI_CTRL_ARREADY;
    sc_in< sc_uint<C_S_AXI_AXI_CTRL_ADDR_WIDTH> > s_axi_AXI_CTRL_ARADDR;
    sc_out< sc_logic > s_axi_AXI_CTRL_RVALID;
    sc_in< sc_logic > s_axi_AXI_CTRL_RREADY;
    sc_out< sc_uint<C_S_AXI_AXI_CTRL_DATA_WIDTH> > s_axi_AXI_CTRL_RDATA;
    sc_out< sc_lv<2> > s_axi_AXI_CTRL_RRESP;
    sc_out< sc_logic > s_axi_AXI_CTRL_BVALID;
    sc_in< sc_logic > s_axi_AXI_CTRL_BREADY;
    sc_out< sc_lv<2> > s_axi_AXI_CTRL_BRESP;
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst_n;
    sc_out< sc_logic > interrupt;
    // Port declarations for the virtual clock. 
    sc_in_clk ap_virtual_clock;


    // Module declarations
    adder(sc_module_name name);
    SC_HAS_PROCESS(adder);

    ~adder();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    adder_AXI_CTRL_s_axi<C_S_AXI_AXI_CTRL_ADDR_WIDTH,C_S_AXI_AXI_CTRL_DATA_WIDTH>* adder_AXI_CTRL_s_axi_U;
    sc_signal< sc_logic > ap_start;
    sc_signal< sc_logic > ap_done;
    sc_signal< sc_logic > ap_idle;
    sc_signal< sc_logic > ap_ready;
    sc_signal< sc_lv<32> > a;
    sc_signal< sc_lv<32> > b;
    sc_signal< sc_lv<32> > c;
    sc_signal< sc_logic > c_ap_vld;
    sc_signal< sc_logic > ap_rst_n_inv;
    sc_signal< sc_logic > adder_AXI_CTRL_s_axi_U_ap_dummy_ce;
    static const sc_logic ap_const_logic_1;
    static const int C_DATA_WIDTH;
    static const sc_logic ap_const_logic_0;
    // Thread declarations
    void thread_adder_AXI_CTRL_s_axi_U_ap_dummy_ce();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_rst_n_inv();
    void thread_c();
    void thread_c_ap_vld();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
