// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.4
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#1 "/home/alok/Vivado_Projects/MSadri/AXI_STREAM_HLS_S06/HLS/simple_axi_stream_counter/.settings/axi_stream.cpp"
#1 "<built-in>"
#1 "<command-line>"
#1 "/home/alok/Vivado_Projects/MSadri/AXI_STREAM_HLS_S06/HLS/simple_axi_stream_counter/.settings/axi_stream.cpp"





#ifndef HLS_FASTSIM
#include "apatb_axi_stream_counter.h"
#endif
#define axi_stream_counter(...) AESL_ORIG_DUT_axi_stream_counter(__VA_ARGS__)
#5 "/home/alok/Vivado_Projects/MSadri/AXI_STREAM_HLS_S06/HLS/simple_axi_stream_counter/.settings/axi_stream.cpp"
int axi_stream_counter(int *counter ) {

 static int counterValue=0;
 counterValue++;
 *counter=counterValue;
 return 0;
}
#undef axi_stream_counter

#11 "/home/alok/Vivado_Projects/MSadri/AXI_STREAM_HLS_S06/HLS/simple_axi_stream_counter/.settings/axi_stream.cpp"
