webtalk_init -webtalk_dir /home/alok/s09/axi_dma_sg/vivado/project_1/project_1.sdk/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sat Apr 2 14:48:06 2016" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2014.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2014.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211154620_0_0_506" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "hul9khu23vcr72c5i7trtpomt7" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2014.4_9" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "9" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 14.04.4 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i3-4150 CPU @ 3.50GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3500.000 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "4.000 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1459579455000" -context "sdk\\\\application/1459579455000"
webtalk_add_data -client sdk -key hwid -value "1459508146000" -context "sdk\\\\application/1459579455000"
webtalk_add_data -client sdk -key bspid -value "1459511551000" -context "sdk\\\\application/1459579455000"
webtalk_add_data -client sdk -key newbsp -value "false" -context "sdk\\\\application/1459579455000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1459579455000"
webtalk_add_data -client sdk -key apptemplate -value "peripheral_tests" -context "sdk\\\\application/1459579455000"
webtalk_transmit -clientid 3935679179 -regid "211154620_0_0_506" -xml /home/alok/s09/axi_dma_sg/vivado/project_1/project_1.sdk/webtalk/usage_statistics_ext_sdk.xml -html /home/alok/s09/axi_dma_sg/vivado/project_1/project_1.sdk/webtalk/usage_statistics_ext_sdk.html -wdm /home/alok/s09/axi_dma_sg/vivado/project_1/project_1.sdk/webtalk/sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
