// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.4
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module image_filter_Loop_1_proc (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        rows,
        cols,
        img_0_data_stream_0_V_dout,
        img_0_data_stream_0_V_empty_n,
        img_0_data_stream_0_V_read,
        img_0_data_stream_1_V_dout,
        img_0_data_stream_1_V_empty_n,
        img_0_data_stream_1_V_read,
        img_0_data_stream_2_V_dout,
        img_0_data_stream_2_V_empty_n,
        img_0_data_stream_2_V_read,
        img_1_data_stream_0_V_din,
        img_1_data_stream_0_V_full_n,
        img_1_data_stream_0_V_write,
        img_1_data_stream_1_V_din,
        img_1_data_stream_1_V_full_n,
        img_1_data_stream_1_V_write,
        img_1_data_stream_2_V_din,
        img_1_data_stream_2_V_full_n,
        img_1_data_stream_2_V_write
);

parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_ST_st1_fsm_0 = 4'b1;
parameter    ap_ST_st2_fsm_1 = 4'b10;
parameter    ap_ST_pp0_stg0_fsm_2 = 4'b100;
parameter    ap_ST_st14_fsm_3 = 4'b1000;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv1_1 = 1'b1;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv1_0 = 1'b0;
parameter    ap_const_lv32_2 = 32'b10;
parameter    ap_const_lv11_0 = 11'b00000000000;
parameter    ap_const_lv32_3 = 32'b11;
parameter    ap_const_lv8_0 = 8'b00000000;
parameter    ap_const_lv11_7FF = 11'b11111111111;
parameter    ap_const_lv11_1 = 11'b1;
parameter    ap_const_lv12_FFF = 12'b111111111111;
parameter    ap_const_lv12_0 = 12'b000000000000;
parameter    ap_const_lv13_19 = 13'b11001;
parameter    ap_const_lv10_80 = 10'b10000000;
parameter    ap_const_lv6_0 = 6'b000000;
parameter    ap_const_lv7_0 = 7'b0000000;
parameter    ap_const_lv32_8 = 32'b1000;
parameter    ap_const_lv32_F = 32'b1111;
parameter    ap_const_lv8_10 = 8'b10000;
parameter    ap_const_lv22_556 = 22'b10101010110;
parameter    ap_const_lv8_37 = 8'b110111;
parameter    ap_const_lv8_CD = 8'b11001101;
parameter    ap_const_lv32_C = 32'b1100;
parameter    ap_const_lv32_14 = 32'b10100;
parameter    ap_const_lv32_13 = 32'b10011;
parameter    ap_const_lv8_FF = 8'b11111111;
parameter    ap_const_lv9_3C = 9'b111100;
parameter    ap_const_lv9_22 = 9'b100010;
parameter    ap_true = 1'b1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [31:0] rows;
input  [31:0] cols;
input  [7:0] img_0_data_stream_0_V_dout;
input   img_0_data_stream_0_V_empty_n;
output   img_0_data_stream_0_V_read;
input  [7:0] img_0_data_stream_1_V_dout;
input   img_0_data_stream_1_V_empty_n;
output   img_0_data_stream_1_V_read;
input  [7:0] img_0_data_stream_2_V_dout;
input   img_0_data_stream_2_V_empty_n;
output   img_0_data_stream_2_V_read;
output  [7:0] img_1_data_stream_0_V_din;
input   img_1_data_stream_0_V_full_n;
output   img_1_data_stream_0_V_write;
output  [7:0] img_1_data_stream_1_V_din;
input   img_1_data_stream_1_V_full_n;
output   img_1_data_stream_1_V_write;
output  [7:0] img_1_data_stream_2_V_din;
input   img_1_data_stream_2_V_full_n;
output   img_1_data_stream_2_V_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg img_0_data_stream_0_V_read;
reg img_0_data_stream_1_V_read;
reg img_0_data_stream_2_V_read;
reg img_1_data_stream_0_V_write;
reg img_1_data_stream_1_V_write;
reg img_1_data_stream_2_V_write;
reg    ap_done_reg = 1'b0;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm = 4'b1;
reg    ap_sig_cseq_ST_st1_fsm_0;
reg    ap_sig_bdd_23;
reg   [10:0] col_reg_357;
wire   [11:0] tmp_15_cast_fu_390_p1;
reg    ap_sig_bdd_65;
wire   [11:0] tmp_16_cast_fu_404_p1;
wire   [10:0] tmp_9_fu_408_p2;
wire   [10:0] tmp_10_fu_414_p2;
wire   [11:0] tmp_21_fu_420_p1;
wire   [11:0] tmp_24_fu_424_p1;
wire   [0:0] exitcond1_fu_432_p2;
reg    ap_sig_cseq_ST_st2_fsm_1;
reg    ap_sig_bdd_85;
wire   [10:0] row_1_fu_437_p2;
reg   [10:0] row_1_reg_1360;
wire   [0:0] tmp_11_fu_443_p2;
reg   [0:0] tmp_11_reg_1365;
wire   [0:0] tmp_12_fu_454_p2;
reg   [0:0] tmp_12_reg_1370;
wire   [0:0] tmp_13_fu_460_p2;
reg   [0:0] tmp_13_reg_1375;
wire   [0:0] tmp_s_fu_466_p2;
reg   [0:0] tmp_s_reg_1380;
wire   [0:0] exitcond_fu_471_p2;
reg   [0:0] exitcond_reg_1385;
reg    ap_sig_cseq_ST_pp0_stg0_fsm_2;
reg    ap_sig_bdd_107;
reg    ap_reg_ppiten_pp0_it0 = 1'b0;
reg   [0:0] or_cond_reg_1394;
reg    ap_sig_bdd_124;
reg    ap_reg_ppiten_pp0_it1 = 1'b0;
reg    ap_reg_ppiten_pp0_it2 = 1'b0;
reg    ap_reg_ppiten_pp0_it3 = 1'b0;
reg    ap_reg_ppiten_pp0_it4 = 1'b0;
reg    ap_reg_ppiten_pp0_it5 = 1'b0;
reg    ap_reg_ppiten_pp0_it6 = 1'b0;
reg    ap_reg_ppiten_pp0_it7 = 1'b0;
reg    ap_reg_ppiten_pp0_it8 = 1'b0;
reg    ap_reg_ppiten_pp0_it9 = 1'b0;
reg   [0:0] or_cond2_reg_1444;
reg   [0:0] ap_reg_ppstg_or_cond2_reg_1444_pp0_it9;
reg    ap_sig_bdd_156;
reg    ap_reg_ppiten_pp0_it10 = 1'b0;
reg   [0:0] ap_reg_ppstg_exitcond_reg_1385_pp0_it1;
reg   [0:0] ap_reg_ppstg_exitcond_reg_1385_pp0_it2;
reg   [0:0] ap_reg_ppstg_exitcond_reg_1385_pp0_it3;
reg   [0:0] ap_reg_ppstg_exitcond_reg_1385_pp0_it4;
reg   [0:0] ap_reg_ppstg_exitcond_reg_1385_pp0_it5;
reg   [0:0] ap_reg_ppstg_exitcond_reg_1385_pp0_it6;
reg   [0:0] ap_reg_ppstg_exitcond_reg_1385_pp0_it7;
reg   [0:0] ap_reg_ppstg_exitcond_reg_1385_pp0_it8;
wire   [10:0] col_1_fu_476_p2;
wire   [0:0] or_cond_fu_491_p2;
reg   [10:0] line_buffer_1_0_val_addr_reg_1398;
reg   [10:0] ap_reg_ppstg_line_buffer_1_0_val_addr_reg_1398_pp0_it1;
reg   [10:0] line_buffer_1_1_val_addr_reg_1404;
reg   [10:0] ap_reg_ppstg_line_buffer_1_1_val_addr_reg_1404_pp0_it1;
reg   [10:0] line_buffer_1_2_val_addr_reg_1410;
reg   [10:0] line_buffer_0_0_val_addr_reg_1416;
reg   [10:0] ap_reg_ppstg_line_buffer_0_0_val_addr_reg_1416_pp0_it1;
reg   [10:0] line_buffer_0_1_val_addr_reg_1422;
reg   [10:0] ap_reg_ppstg_line_buffer_0_1_val_addr_reg_1422_pp0_it1;
reg   [10:0] line_buffer_0_2_val_addr_reg_1428;
reg   [10:0] ap_reg_ppstg_line_buffer_0_2_val_addr_reg_1428_pp0_it1;
wire   [0:0] tmp10_fu_523_p2;
reg   [0:0] tmp10_reg_1434;
wire   [0:0] tmp11_fu_528_p2;
reg   [0:0] tmp11_reg_1439;
wire   [0:0] or_cond2_fu_539_p2;
reg   [0:0] ap_reg_ppstg_or_cond2_reg_1444_pp0_it1;
reg   [0:0] ap_reg_ppstg_or_cond2_reg_1444_pp0_it2;
reg   [0:0] ap_reg_ppstg_or_cond2_reg_1444_pp0_it3;
reg   [0:0] ap_reg_ppstg_or_cond2_reg_1444_pp0_it4;
reg   [0:0] ap_reg_ppstg_or_cond2_reg_1444_pp0_it5;
reg   [0:0] ap_reg_ppstg_or_cond2_reg_1444_pp0_it6;
reg   [0:0] ap_reg_ppstg_or_cond2_reg_1444_pp0_it7;
reg   [0:0] ap_reg_ppstg_or_cond2_reg_1444_pp0_it8;
wire   [7:0] line_buffer_0_2_val_q0;
reg   [7:0] pix_val_2_reg_1453;
reg   [7:0] ap_reg_ppstg_pix_val_2_reg_1453_pp0_it2;
reg   [7:0] ap_reg_ppstg_pix_val_2_reg_1453_pp0_it3;
wire   [0:0] or_cond3_fu_569_p2;
reg   [0:0] or_cond3_reg_1459;
reg   [0:0] ap_reg_ppstg_or_cond3_reg_1459_pp0_it2;
reg   [0:0] ap_reg_ppstg_or_cond3_reg_1459_pp0_it3;
reg   [0:0] ap_reg_ppstg_or_cond3_reg_1459_pp0_it4;
reg   [0:0] ap_reg_ppstg_or_cond3_reg_1459_pp0_it5;
reg   [0:0] ap_reg_ppstg_or_cond3_reg_1459_pp0_it6;
reg   [0:0] ap_reg_ppstg_or_cond3_reg_1459_pp0_it7;
reg   [0:0] ap_reg_ppstg_or_cond3_reg_1459_pp0_it8;
reg   [7:0] G_5_reg_1463;
reg   [7:0] ap_reg_ppstg_G_5_reg_1463_pp0_it3;
reg   [7:0] R_5_reg_1469;
wire   [7:0] line_buffer_1_0_val_q0;
reg   [7:0] R_reg_1475;
wire   [7:0] line_buffer_1_1_val_q0;
reg   [7:0] G_reg_1480;
wire   [9:0] tmp1_fu_597_p2;
reg   [9:0] tmp1_reg_1486;
wire   [7:0] line_buffer_0_0_val_q0;
reg   [7:0] pix_val_0_reg_1491;
reg   [7:0] ap_reg_ppstg_pix_val_0_reg_1491_pp0_it3;
reg   [7:0] ap_reg_ppstg_pix_val_0_reg_1491_pp0_it4;
reg   [7:0] ap_reg_ppstg_pix_val_0_reg_1491_pp0_it5;
reg   [7:0] ap_reg_ppstg_pix_val_0_reg_1491_pp0_it6;
wire   [7:0] line_buffer_0_1_val_q0;
reg   [7:0] pix_val_1_reg_1498;
reg   [7:0] ap_reg_ppstg_pix_val_1_reg_1498_pp0_it3;
reg   [7:0] tmp_i_reg_1515;
wire   [9:0] tmp4_fu_703_p2;
reg   [9:0] tmp4_reg_1520;
wire   [14:0] tmp_6_i2_fu_741_p2;
reg   [14:0] tmp_6_i2_reg_1525;
reg   [7:0] y_window_2_2_1_reg_1530;
reg   [7:0] ap_reg_ppstg_y_window_2_2_1_reg_1530_pp0_it5;
wire   [7:0] y_window_2_1_2_fu_750_p2;
reg   [7:0] y_window_2_1_2_reg_1536;
reg   [7:0] ap_reg_ppstg_y_window_2_1_2_reg_1536_pp0_it5;
reg   [7:0] tmp_i1_reg_1541;
reg   [7:0] tmp_i2_reg_1546;
wire   [8:0] tmp_2_i3_fu_880_p2;
reg   [8:0] tmp_2_i3_reg_1551;
reg   [8:0] ap_reg_ppstg_tmp_2_i3_reg_1551_pp0_it5;
reg   [8:0] ap_reg_ppstg_tmp_2_i3_reg_1551_pp0_it6;
wire   [7:0] y_window_1_1_1_fu_891_p2;
reg   [7:0] y_window_1_1_1_reg_1556;
wire   [8:0] x_weight_2_0_2_i_fu_927_p2;
reg   [8:0] x_weight_2_0_2_i_reg_1562;
wire   [9:0] y_weight_2_1_2_i_fu_943_p2;
reg   [9:0] y_weight_2_1_2_i_reg_1567;
wire  signed [10:0] x_weight_2_2_2_i_fu_1045_p2;
reg  signed [10:0] x_weight_2_2_2_i_reg_1572;
wire   [10:0] y_weight_2_2_2_i_fu_1051_p2;
reg   [10:0] y_weight_2_2_2_i_reg_1577;
wire   [7:0] tmp_28_fu_1057_p1;
reg   [7:0] tmp_28_reg_1582;
wire   [7:0] tmp_29_fu_1061_p1;
reg   [7:0] tmp_29_reg_1588;
wire   [7:0] edge_weight_i_fu_1115_p2;
reg   [7:0] edge_weight_i_reg_1594;
reg   [7:0] ap_reg_ppstg_edge_weight_i_reg_1594_pp0_it8;
wire   [0:0] tmp_15_i_fu_1143_p2;
reg   [0:0] tmp_15_i_reg_1606;
wire   [0:0] tmp_17_i_fu_1148_p2;
reg   [0:0] tmp_17_i_reg_1612;
reg   [8:0] B_cast_i_reg_1617;
reg   [7:0] sepia_val_0_reg_1623;
reg   [7:0] ap_reg_ppstg_sepia_val_0_reg_1623_pp0_it9;
wire   [7:0] edge_val_1_fu_1195_p3;
wire   [7:0] sepia_val_2_fu_1225_p3;
reg   [7:0] sepia_val_2_reg_1633;
wire   [7:0] sepia_val_1_fu_1245_p3;
reg   [7:0] sepia_val_1_reg_1638;
wire   [10:0] line_buffer_0_0_val_address0;
reg    line_buffer_0_0_val_ce0;
wire   [10:0] line_buffer_0_0_val_address1;
reg    line_buffer_0_0_val_ce1;
reg    line_buffer_0_0_val_we1;
wire   [7:0] line_buffer_0_0_val_d1;
wire   [10:0] line_buffer_0_1_val_address0;
reg    line_buffer_0_1_val_ce0;
wire   [10:0] line_buffer_0_1_val_address1;
reg    line_buffer_0_1_val_ce1;
reg    line_buffer_0_1_val_we1;
wire   [7:0] line_buffer_0_1_val_d1;
wire   [10:0] line_buffer_0_2_val_address0;
reg    line_buffer_0_2_val_ce0;
wire   [10:0] line_buffer_0_2_val_address1;
reg    line_buffer_0_2_val_ce1;
reg    line_buffer_0_2_val_we1;
wire   [7:0] line_buffer_0_2_val_d1;
wire   [10:0] line_buffer_1_0_val_address0;
reg    line_buffer_1_0_val_ce0;
wire   [10:0] line_buffer_1_0_val_address1;
reg    line_buffer_1_0_val_ce1;
reg    line_buffer_1_0_val_we1;
wire   [7:0] line_buffer_1_0_val_d1;
wire   [10:0] line_buffer_1_1_val_address0;
reg    line_buffer_1_1_val_ce0;
wire   [10:0] line_buffer_1_1_val_address1;
reg    line_buffer_1_1_val_ce1;
reg    line_buffer_1_1_val_we1;
wire   [7:0] line_buffer_1_1_val_d1;
wire   [10:0] line_buffer_1_2_val_address0;
reg    line_buffer_1_2_val_ce0;
wire   [7:0] line_buffer_1_2_val_q0;
wire   [10:0] line_buffer_1_2_val_address1;
reg    line_buffer_1_2_val_ce1;
reg    line_buffer_1_2_val_we1;
wire   [7:0] line_buffer_1_2_val_d1;
reg   [10:0] row_reg_346;
reg    ap_sig_cseq_ST_st14_fsm_3;
reg    ap_sig_bdd_429;
reg   [7:0] ap_reg_phiprechg_edge_val1_reg_368pp0_it9;
reg   [7:0] ap_reg_phiprechg_edge_val1_reg_368pp0_it10;
wire   [7:0] ap_reg_phiprechg_edge_val1_reg_368pp0_it1;
reg   [7:0] ap_reg_phiprechg_edge_val1_reg_368pp0_it2;
reg   [7:0] ap_reg_phiprechg_edge_val1_reg_368pp0_it3;
reg   [7:0] ap_reg_phiprechg_edge_val1_reg_368pp0_it4;
reg   [7:0] ap_reg_phiprechg_edge_val1_reg_368pp0_it5;
reg   [7:0] ap_reg_phiprechg_edge_val1_reg_368pp0_it6;
reg   [7:0] ap_reg_phiprechg_edge_val1_reg_368pp0_it7;
reg   [7:0] ap_reg_phiprechg_edge_val1_reg_368pp0_it8;
wire   [63:0] tmp_16_fu_496_p1;
reg   [7:0] B_2_fu_152;
reg   [7:0] G_2_fu_156;
reg   [7:0] y_window_0_1_fu_160;
wire   [7:0] y_window_0_1_1_fu_896_p2;
reg   [7:0] y_window_0_2_fu_164;
reg   [7:0] R_2_fu_168;
reg   [7:0] y_window_1_1_fu_172;
reg   [7:0] y_window_1_2_fu_176;
reg   [7:0] y_window_2_2_fu_180;
reg   [7:0] y_window_2_1_fu_184;
wire   [10:0] tmp_fu_380_p1;
wire   [10:0] tmp_7_fu_384_p2;
wire   [10:0] tmp_2_fu_394_p1;
wire   [10:0] tmp_8_fu_398_p2;
wire   [11:0] row_cast_fu_428_p1;
wire   [11:0] output_row_fu_448_p2;
wire   [11:0] col_cast_fu_482_p1;
wire   [0:0] tmp_14_fu_486_p2;
wire   [11:0] output_col_fu_506_p2;
wire   [0:0] tmp_17_fu_512_p2;
wire   [0:0] tmp_18_fu_518_p2;
wire   [0:0] tmp_19_fu_533_p2;
wire   [7:0] grp_fu_563_p0;
wire   [5:0] grp_fu_563_p1;
wire   [8:0] p_shl2_i_fu_585_p3;
wire   [9:0] p_shl2_cast_i_cast_fu_593_p1;
wire   [7:0] grp_fu_606_p0;
wire   [5:0] grp_fu_606_p1;
wire   [7:0] grp_fu_616_p0;
wire   [5:0] grp_fu_616_p1;
wire   [13:0] p_shl1_i_fu_622_p3;
wire   [14:0] p_shl_i_fu_636_p3;
wire   [14:0] tmp55_cast_fu_647_p1;
wire   [14:0] p_shl1_cast_i_fu_629_p1;
wire   [14:0] tmp_6_i_fu_650_p2;
wire   [15:0] p_shl_cast_i_fu_643_p1;
wire   [15:0] tmp_6_cast_i_fu_656_p1;
wire   [12:0] grp_fu_563_p2;
wire   [12:0] tmp_2_cast3_i_cast_fu_633_p1;
wire   [12:0] tmp3_fu_666_p2;
wire   [15:0] tmp57_cast_fu_672_p1;
wire   [15:0] tmp2_fu_660_p2;
(* use_dsp48 = "no" *) wire   [15:0] tmp_8_i_fu_676_p2;
wire   [8:0] p_shl2_i6_fu_692_p3;
wire   [9:0] p_shl2_cast_i7_cast_fu_699_p1;
wire   [13:0] p_shl1_i1_fu_709_p3;
wire   [8:0] p_shl2_i1_fu_720_p3;
wire   [9:0] p_shl2_cast_i29_cast_fu_727_p1;
wire   [9:0] tmp7_fu_731_p2;
wire   [14:0] tmp61_cast_fu_737_p1;
wire   [14:0] p_shl1_cast_i1_fu_716_p1;
wire   [13:0] p_shl1_i4_fu_755_p3;
wire   [14:0] p_shl_i1_fu_769_p3;
wire   [14:0] tmp58_cast_fu_780_p1;
wire   [14:0] p_shl1_cast_i5_fu_762_p1;
wire   [14:0] tmp_6_i1_fu_783_p2;
wire   [15:0] p_shl_cast_i1_fu_776_p1;
wire   [15:0] tmp_6_cast_i1_fu_789_p1;
wire   [12:0] grp_fu_606_p2;
wire   [12:0] tmp_2_cast3_i9_cast_fu_766_p1;
wire   [12:0] tmp6_fu_799_p2;
wire   [15:0] tmp60_cast_fu_805_p1;
wire   [15:0] tmp5_fu_793_p2;
(* use_dsp48 = "no" *) wire   [15:0] tmp_8_i1_fu_809_p2;
wire   [14:0] p_shl_i2_fu_828_p3;
wire   [15:0] p_shl_cast_i2_fu_835_p1;
wire   [15:0] tmp_6_cast_i2_fu_839_p1;
wire   [12:0] grp_fu_616_p2;
wire   [12:0] tmp_2_cast3_i31_cast_fu_825_p1;
wire   [12:0] tmp9_fu_848_p2;
wire   [15:0] tmp63_cast_fu_854_p1;
wire   [15:0] tmp8_fu_842_p2;
(* use_dsp48 = "no" *) wire   [15:0] tmp_8_i2_fu_858_p2;
wire   [8:0] tmp_cast_i_fu_877_p1;
wire   [8:0] tmp_cast_i2_fu_874_p1;
wire   [8:0] tmp_23_0_1_i_fu_911_p3;
wire   [8:0] tmp_19_0_2_cast8_i_cast_fu_923_p1;
wire   [8:0] tmp_19_0_cast9_i_cast_fu_907_p1;
wire   [8:0] tmp12_fu_933_p2;
wire   [9:0] tmp66_cast_fu_939_p1;
wire   [9:0] tmp_23_0_1_cast_i_fu_919_p1;
wire   [8:0] p_shl8_i_fu_971_p3;
wire  signed [10:0] x_weight_2_0_2_cast_i_fu_968_p1;
wire   [10:0] p_shl8_cast_i_fu_978_p1;
wire   [8:0] tmp_21_1_2_i_fu_988_p3;
wire  signed [10:0] x_weight_2_1_1_i_fu_982_p2;
wire   [10:0] tmp_21_1_2_cast_i_fu_996_p1;
wire  signed [10:0] x_weight_2_1_2_i_fu_1000_p2;
wire   [10:0] tmp_19_2_cast_i_fu_1009_p1;
wire   [10:0] y_weight_2_1_2_cast_i_fu_1006_p1;
wire   [8:0] p_shl_i3_fu_1024_p3;
wire   [10:0] y_weight_2_2_i_fu_1018_p2;
wire   [10:0] p_shl_cast_i3_fu_1031_p1;
wire  signed [10:0] x_weight_2_2_i_fu_1012_p2;
wire   [10:0] tmp_19_2_2_cast_i_fu_1041_p1;
wire   [10:0] y_weight_2_2_1_i_fu_1035_p2;
wire   [0:0] tmp_i_29_fu_1081_p2;
wire   [7:0] tmp_22_fu_1086_p2;
wire   [0:0] tmp_11_i_fu_1098_p2;
wire   [7:0] tmp_25_fu_1103_p2;
wire   [7:0] tmp_26_fu_1108_p3;
wire   [7:0] tmp_23_fu_1091_p3;
wire   [9:0] tmp_2_cast_i3_fu_1124_p1;
wire   [9:0] tmp_1_cast_i_fu_1121_p1;
wire   [9:0] tmp_3_i_fu_1127_p2;
wire   [9:0] grp_fu_1137_p0;
wire   [11:0] grp_fu_1137_p1;
wire   [21:0] grp_fu_1137_p2;
wire   [0:0] not_tmp_15_i_fu_1178_p2;
wire   [0:0] tmp_27_fu_1191_p2;
wire   [7:0] p_i_cast_fu_1183_p3;
wire   [7:0] edge_val_fu_1173_p2;
wire   [8:0] R_3_fu_1203_p2;
wire   [0:0] tmp_30_fu_1213_p3;
wire   [7:0] tmp_31_fu_1221_p1;
wire   [8:0] G_3_fu_1208_p2;
wire   [0:0] tmp_32_fu_1233_p3;
wire   [7:0] tmp_33_fu_1241_p1;
reg    grp_fu_563_ce;
reg    grp_fu_606_ce;
reg    grp_fu_616_ce;
reg    grp_fu_1137_ce;
reg   [3:0] ap_NS_fsm;
wire   [21:0] grp_fu_1137_p00;
wire   [12:0] grp_fu_563_p00;
wire   [12:0] grp_fu_606_p00;
wire   [12:0] grp_fu_616_p00;
reg    ap_sig_bdd_349;
reg    ap_sig_bdd_436;
reg    ap_sig_bdd_459;
reg    ap_sig_bdd_444;


image_filter_Loop_1_proc_line_buffer_0_0_val #(
    .DataWidth( 8 ),
    .AddressRange( 1921 ),
    .AddressWidth( 11 ))
line_buffer_0_0_val_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( line_buffer_0_0_val_address0 ),
    .ce0( line_buffer_0_0_val_ce0 ),
    .q0( line_buffer_0_0_val_q0 ),
    .address1( line_buffer_0_0_val_address1 ),
    .ce1( line_buffer_0_0_val_ce1 ),
    .we1( line_buffer_0_0_val_we1 ),
    .d1( line_buffer_0_0_val_d1 )
);

image_filter_Loop_1_proc_line_buffer_0_0_val #(
    .DataWidth( 8 ),
    .AddressRange( 1921 ),
    .AddressWidth( 11 ))
line_buffer_0_1_val_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( line_buffer_0_1_val_address0 ),
    .ce0( line_buffer_0_1_val_ce0 ),
    .q0( line_buffer_0_1_val_q0 ),
    .address1( line_buffer_0_1_val_address1 ),
    .ce1( line_buffer_0_1_val_ce1 ),
    .we1( line_buffer_0_1_val_we1 ),
    .d1( line_buffer_0_1_val_d1 )
);

image_filter_Loop_1_proc_line_buffer_0_0_val #(
    .DataWidth( 8 ),
    .AddressRange( 1921 ),
    .AddressWidth( 11 ))
line_buffer_0_2_val_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( line_buffer_0_2_val_address0 ),
    .ce0( line_buffer_0_2_val_ce0 ),
    .q0( line_buffer_0_2_val_q0 ),
    .address1( line_buffer_0_2_val_address1 ),
    .ce1( line_buffer_0_2_val_ce1 ),
    .we1( line_buffer_0_2_val_we1 ),
    .d1( line_buffer_0_2_val_d1 )
);

image_filter_Loop_1_proc_line_buffer_0_0_val #(
    .DataWidth( 8 ),
    .AddressRange( 1921 ),
    .AddressWidth( 11 ))
line_buffer_1_0_val_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( line_buffer_1_0_val_address0 ),
    .ce0( line_buffer_1_0_val_ce0 ),
    .q0( line_buffer_1_0_val_q0 ),
    .address1( line_buffer_1_0_val_address1 ),
    .ce1( line_buffer_1_0_val_ce1 ),
    .we1( line_buffer_1_0_val_we1 ),
    .d1( line_buffer_1_0_val_d1 )
);

image_filter_Loop_1_proc_line_buffer_0_0_val #(
    .DataWidth( 8 ),
    .AddressRange( 1921 ),
    .AddressWidth( 11 ))
line_buffer_1_1_val_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( line_buffer_1_1_val_address0 ),
    .ce0( line_buffer_1_1_val_ce0 ),
    .q0( line_buffer_1_1_val_q0 ),
    .address1( line_buffer_1_1_val_address1 ),
    .ce1( line_buffer_1_1_val_ce1 ),
    .we1( line_buffer_1_1_val_we1 ),
    .d1( line_buffer_1_1_val_d1 )
);

image_filter_Loop_1_proc_line_buffer_0_0_val #(
    .DataWidth( 8 ),
    .AddressRange( 1921 ),
    .AddressWidth( 11 ))
line_buffer_1_2_val_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( line_buffer_1_2_val_address0 ),
    .ce0( line_buffer_1_2_val_ce0 ),
    .q0( line_buffer_1_2_val_q0 ),
    .address1( line_buffer_1_2_val_address1 ),
    .ce1( line_buffer_1_2_val_ce1 ),
    .we1( line_buffer_1_2_val_we1 ),
    .d1( line_buffer_1_2_val_d1 )
);

image_filter_mul_8ns_6ns_13_3 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 13 ))
image_filter_mul_8ns_6ns_13_3_U15(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_563_p0 ),
    .din1( grp_fu_563_p1 ),
    .ce( grp_fu_563_ce ),
    .dout( grp_fu_563_p2 )
);

image_filter_mul_8ns_6ns_13_3 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 13 ))
image_filter_mul_8ns_6ns_13_3_U16(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_606_p0 ),
    .din1( grp_fu_606_p1 ),
    .ce( grp_fu_606_ce ),
    .dout( grp_fu_606_p2 )
);

image_filter_mul_8ns_6ns_13_3 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 13 ))
image_filter_mul_8ns_6ns_13_3_U17(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_616_p0 ),
    .din1( grp_fu_616_p1 ),
    .ce( grp_fu_616_ce ),
    .dout( grp_fu_616_p2 )
);

image_filter_mul_10ns_12ns_22_2 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 22 ))
image_filter_mul_10ns_12ns_22_2_U18(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_1137_p0 ),
    .din1( grp_fu_1137_p1 ),
    .ce( grp_fu_1137_ce ),
    .dout( grp_fu_1137_p2 )
);



/// the current state (ap_CS_fsm) of the state machine. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_CS_fsm
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_st1_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

/// ap_done_reg assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_done_reg
    if (ap_rst == 1'b1) begin
        ap_done_reg <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_continue)) begin
            ap_done_reg <= ap_const_logic_0;
        end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & ~(exitcond1_fu_432_p2 == ap_const_lv1_0))) begin
            ap_done_reg <= ap_const_logic_1;
        end
    end
end

/// ap_reg_ppiten_pp0_it0 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it0
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it0 <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_156 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it10))) & ~(ap_const_lv1_0 == exitcond_fu_471_p2))) begin
            ap_reg_ppiten_pp0_it0 <= ap_const_logic_0;
        end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & (exitcond1_fu_432_p2 == ap_const_lv1_0))) begin
            ap_reg_ppiten_pp0_it0 <= ap_const_logic_1;
        end
    end
end

/// ap_reg_ppiten_pp0_it1 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it1
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_156 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it10))))) begin
            ap_reg_ppiten_pp0_it1 <= ap_reg_ppiten_pp0_it0;
        end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & (exitcond1_fu_432_p2 == ap_const_lv1_0))) begin
            ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
        end
    end
end

/// ap_reg_ppiten_pp0_it10 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it10
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it10 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_156 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it10)))) begin
            ap_reg_ppiten_pp0_it10 <= ap_reg_ppiten_pp0_it9;
        end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & (exitcond1_fu_432_p2 == ap_const_lv1_0))) begin
            ap_reg_ppiten_pp0_it10 <= ap_const_logic_0;
        end
    end
end

/// ap_reg_ppiten_pp0_it2 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it2
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it2 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_156 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it10)))) begin
            ap_reg_ppiten_pp0_it2 <= ap_reg_ppiten_pp0_it1;
        end
    end
end

/// ap_reg_ppiten_pp0_it3 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it3
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it3 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_156 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it10)))) begin
            ap_reg_ppiten_pp0_it3 <= ap_reg_ppiten_pp0_it2;
        end
    end
end

/// ap_reg_ppiten_pp0_it4 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it4
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it4 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_156 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it10)))) begin
            ap_reg_ppiten_pp0_it4 <= ap_reg_ppiten_pp0_it3;
        end
    end
end

/// ap_reg_ppiten_pp0_it5 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it5
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it5 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_156 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it10)))) begin
            if (~(ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) begin
                ap_reg_ppiten_pp0_it5 <= ap_const_logic_0;
            end else if ((ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) begin
                ap_reg_ppiten_pp0_it5 <= ap_reg_ppiten_pp0_it4;
            end
        end
    end
end

/// ap_reg_ppiten_pp0_it6 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it6
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it6 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_156 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it10)))) begin
            ap_reg_ppiten_pp0_it6 <= ap_reg_ppiten_pp0_it5;
        end
    end
end

/// ap_reg_ppiten_pp0_it7 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it7
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it7 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_156 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it10)))) begin
            ap_reg_ppiten_pp0_it7 <= ap_reg_ppiten_pp0_it6;
        end
    end
end

/// ap_reg_ppiten_pp0_it8 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it8
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it8 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_156 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it10)))) begin
            ap_reg_ppiten_pp0_it8 <= ap_reg_ppiten_pp0_it7;
        end
    end
end

/// ap_reg_ppiten_pp0_it9 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it9
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it9 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_156 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it10)))) begin
            ap_reg_ppiten_pp0_it9 <= ap_reg_ppiten_pp0_it8;
        end
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (ap_sig_bdd_436) begin
        if (ap_sig_bdd_349) begin
            ap_reg_phiprechg_edge_val1_reg_368pp0_it10 <= edge_val_1_fu_1195_p3;
        end else if ((ap_true == ap_true)) begin
            ap_reg_phiprechg_edge_val1_reg_368pp0_it10 <= ap_reg_phiprechg_edge_val1_reg_368pp0_it9;
        end
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (ap_sig_bdd_444) begin
        if (ap_sig_bdd_459) begin
            ap_reg_phiprechg_edge_val1_reg_368pp0_it2 <= ap_const_lv8_0;
        end else if ((ap_true == ap_true)) begin
            ap_reg_phiprechg_edge_val1_reg_368pp0_it2 <= ap_reg_phiprechg_edge_val1_reg_368pp0_it1;
        end
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_156 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it10))) & (ap_const_lv1_0 == exitcond_fu_471_p2))) begin
        col_reg_357 <= col_1_fu_476_p2;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & (exitcond1_fu_432_p2 == ap_const_lv1_0))) begin
        col_reg_357 <= ap_const_lv11_0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st14_fsm_3)) begin
        row_reg_346 <= row_1_reg_1360;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~ap_sig_bdd_65)) begin
        row_reg_346 <= ap_const_lv11_0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (ap_const_lv1_0 == exitcond_reg_1385) & ~(ap_const_lv1_0 == or_cond_reg_1394) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_156 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it10))))) begin
        B_2_fu_152 <= img_0_data_stream_2_V_dout;
        G_2_fu_156 <= img_0_data_stream_1_V_dout;
        R_2_fu_168 <= img_0_data_stream_0_V_dout;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_156 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it10)))) begin
        B_cast_i_reg_1617 <= {{grp_fu_1137_p2[ap_const_lv32_14 : ap_const_lv32_C]}};
        ap_reg_ppstg_G_5_reg_1463_pp0_it3 <= G_5_reg_1463;
        ap_reg_ppstg_edge_weight_i_reg_1594_pp0_it8 <= edge_weight_i_reg_1594;
        ap_reg_ppstg_exitcond_reg_1385_pp0_it2 <= ap_reg_ppstg_exitcond_reg_1385_pp0_it1;
        ap_reg_ppstg_exitcond_reg_1385_pp0_it3 <= ap_reg_ppstg_exitcond_reg_1385_pp0_it2;
        ap_reg_ppstg_exitcond_reg_1385_pp0_it4 <= ap_reg_ppstg_exitcond_reg_1385_pp0_it3;
        ap_reg_ppstg_exitcond_reg_1385_pp0_it5 <= ap_reg_ppstg_exitcond_reg_1385_pp0_it4;
        ap_reg_ppstg_exitcond_reg_1385_pp0_it6 <= ap_reg_ppstg_exitcond_reg_1385_pp0_it5;
        ap_reg_ppstg_exitcond_reg_1385_pp0_it7 <= ap_reg_ppstg_exitcond_reg_1385_pp0_it6;
        ap_reg_ppstg_exitcond_reg_1385_pp0_it8 <= ap_reg_ppstg_exitcond_reg_1385_pp0_it7;
        ap_reg_ppstg_or_cond2_reg_1444_pp0_it2 <= ap_reg_ppstg_or_cond2_reg_1444_pp0_it1;
        ap_reg_ppstg_or_cond2_reg_1444_pp0_it3 <= ap_reg_ppstg_or_cond2_reg_1444_pp0_it2;
        ap_reg_ppstg_or_cond2_reg_1444_pp0_it4 <= ap_reg_ppstg_or_cond2_reg_1444_pp0_it3;
        ap_reg_ppstg_or_cond2_reg_1444_pp0_it5 <= ap_reg_ppstg_or_cond2_reg_1444_pp0_it4;
        ap_reg_ppstg_or_cond2_reg_1444_pp0_it6 <= ap_reg_ppstg_or_cond2_reg_1444_pp0_it5;
        ap_reg_ppstg_or_cond2_reg_1444_pp0_it7 <= ap_reg_ppstg_or_cond2_reg_1444_pp0_it6;
        ap_reg_ppstg_or_cond2_reg_1444_pp0_it8 <= ap_reg_ppstg_or_cond2_reg_1444_pp0_it7;
        ap_reg_ppstg_or_cond2_reg_1444_pp0_it9 <= ap_reg_ppstg_or_cond2_reg_1444_pp0_it8;
        ap_reg_ppstg_or_cond3_reg_1459_pp0_it2 <= or_cond3_reg_1459;
        ap_reg_ppstg_or_cond3_reg_1459_pp0_it3 <= ap_reg_ppstg_or_cond3_reg_1459_pp0_it2;
        ap_reg_ppstg_or_cond3_reg_1459_pp0_it4 <= ap_reg_ppstg_or_cond3_reg_1459_pp0_it3;
        ap_reg_ppstg_or_cond3_reg_1459_pp0_it5 <= ap_reg_ppstg_or_cond3_reg_1459_pp0_it4;
        ap_reg_ppstg_or_cond3_reg_1459_pp0_it6 <= ap_reg_ppstg_or_cond3_reg_1459_pp0_it5;
        ap_reg_ppstg_or_cond3_reg_1459_pp0_it7 <= ap_reg_ppstg_or_cond3_reg_1459_pp0_it6;
        ap_reg_ppstg_or_cond3_reg_1459_pp0_it8 <= ap_reg_ppstg_or_cond3_reg_1459_pp0_it7;
        ap_reg_ppstg_pix_val_0_reg_1491_pp0_it3 <= pix_val_0_reg_1491;
        ap_reg_ppstg_pix_val_0_reg_1491_pp0_it4 <= ap_reg_ppstg_pix_val_0_reg_1491_pp0_it3;
        ap_reg_ppstg_pix_val_0_reg_1491_pp0_it5 <= ap_reg_ppstg_pix_val_0_reg_1491_pp0_it4;
        ap_reg_ppstg_pix_val_0_reg_1491_pp0_it6 <= ap_reg_ppstg_pix_val_0_reg_1491_pp0_it5;
        ap_reg_ppstg_pix_val_1_reg_1498_pp0_it3 <= pix_val_1_reg_1498;
        ap_reg_ppstg_pix_val_2_reg_1453_pp0_it2 <= pix_val_2_reg_1453;
        ap_reg_ppstg_pix_val_2_reg_1453_pp0_it3 <= ap_reg_ppstg_pix_val_2_reg_1453_pp0_it2;
        ap_reg_ppstg_sepia_val_0_reg_1623_pp0_it9 <= sepia_val_0_reg_1623;
        ap_reg_ppstg_tmp_2_i3_reg_1551_pp0_it5 <= tmp_2_i3_reg_1551;
        ap_reg_ppstg_tmp_2_i3_reg_1551_pp0_it6 <= ap_reg_ppstg_tmp_2_i3_reg_1551_pp0_it5;
        ap_reg_ppstg_y_window_2_1_2_reg_1536_pp0_it5 <= y_window_2_1_2_reg_1536;
        ap_reg_ppstg_y_window_2_2_1_reg_1530_pp0_it5 <= y_window_2_2_1_reg_1530;
        sepia_val_0_reg_1623 <= {{grp_fu_1137_p2[ap_const_lv32_13 : ap_const_lv32_C]}};
        sepia_val_1_reg_1638 <= sepia_val_1_fu_1245_p3;
        sepia_val_2_reg_1633 <= sepia_val_2_fu_1225_p3;
        y_window_2_2_1_reg_1530 <= y_window_2_1_fu_184;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_156 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it10))) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_1385_pp0_it1))) begin
        G_5_reg_1463 <= G_2_fu_156;
        G_reg_1480 <= line_buffer_1_1_val_q0;
        R_5_reg_1469 <= R_2_fu_168;
        R_reg_1475 <= line_buffer_1_0_val_q0;
        pix_val_0_reg_1491 <= line_buffer_0_0_val_q0;
        pix_val_1_reg_1498 <= line_buffer_0_1_val_q0;
        tmp1_reg_1486[1] <= tmp1_fu_597_p2[1];
tmp1_reg_1486[2] <= tmp1_fu_597_p2[2];
tmp1_reg_1486[3] <= tmp1_fu_597_p2[3];
tmp1_reg_1486[4] <= tmp1_fu_597_p2[4];
tmp1_reg_1486[5] <= tmp1_fu_597_p2[5];
tmp1_reg_1486[6] <= tmp1_fu_597_p2[6];
tmp1_reg_1486[7] <= tmp1_fu_597_p2[7];
tmp1_reg_1486[8] <= tmp1_fu_597_p2[8];
tmp1_reg_1486[9] <= tmp1_fu_597_p2[9];
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_156 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it10))))) begin
        ap_reg_phiprechg_edge_val1_reg_368pp0_it3 <= ap_reg_phiprechg_edge_val1_reg_368pp0_it2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it3) & ~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_156 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it10))))) begin
        ap_reg_phiprechg_edge_val1_reg_368pp0_it4 <= ap_reg_phiprechg_edge_val1_reg_368pp0_it3;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it4) & ~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_156 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it10))))) begin
        ap_reg_phiprechg_edge_val1_reg_368pp0_it5 <= ap_reg_phiprechg_edge_val1_reg_368pp0_it4;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it5) & ~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_156 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it10))))) begin
        ap_reg_phiprechg_edge_val1_reg_368pp0_it6 <= ap_reg_phiprechg_edge_val1_reg_368pp0_it5;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it6) & ~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_156 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it10))))) begin
        ap_reg_phiprechg_edge_val1_reg_368pp0_it7 <= ap_reg_phiprechg_edge_val1_reg_368pp0_it6;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it7) & ~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_156 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it10))))) begin
        ap_reg_phiprechg_edge_val1_reg_368pp0_it8 <= ap_reg_phiprechg_edge_val1_reg_368pp0_it7;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it8) & ~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_156 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it10))))) begin
        ap_reg_phiprechg_edge_val1_reg_368pp0_it9 <= ap_reg_phiprechg_edge_val1_reg_368pp0_it8;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_156 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it10))))) begin
        ap_reg_ppstg_exitcond_reg_1385_pp0_it1 <= exitcond_reg_1385;
        ap_reg_ppstg_line_buffer_0_0_val_addr_reg_1416_pp0_it1 <= line_buffer_0_0_val_addr_reg_1416;
        ap_reg_ppstg_line_buffer_0_1_val_addr_reg_1422_pp0_it1 <= line_buffer_0_1_val_addr_reg_1422;
        ap_reg_ppstg_line_buffer_0_2_val_addr_reg_1428_pp0_it1 <= line_buffer_0_2_val_addr_reg_1428;
        ap_reg_ppstg_line_buffer_1_0_val_addr_reg_1398_pp0_it1 <= line_buffer_1_0_val_addr_reg_1398;
        ap_reg_ppstg_line_buffer_1_1_val_addr_reg_1404_pp0_it1 <= line_buffer_1_1_val_addr_reg_1404;
        ap_reg_ppstg_or_cond2_reg_1444_pp0_it1 <= or_cond2_reg_1444;
        exitcond_reg_1385 <= exitcond_fu_471_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_156 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it10))) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_1385_pp0_it6) & (ap_const_lv1_0 == ap_reg_ppstg_or_cond3_reg_1459_pp0_it6))) begin
        edge_weight_i_reg_1594 <= edge_weight_i_fu_1115_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_156 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it10))) & (ap_const_lv1_0 == exitcond_fu_471_p2))) begin
        line_buffer_0_0_val_addr_reg_1416 <= tmp_16_fu_496_p1;
        line_buffer_0_1_val_addr_reg_1422 <= tmp_16_fu_496_p1;
        line_buffer_0_2_val_addr_reg_1428 <= tmp_16_fu_496_p1;
        line_buffer_1_0_val_addr_reg_1398 <= tmp_16_fu_496_p1;
        line_buffer_1_1_val_addr_reg_1404 <= tmp_16_fu_496_p1;
        line_buffer_1_2_val_addr_reg_1410 <= tmp_16_fu_496_p1;
        or_cond2_reg_1444 <= or_cond2_fu_539_p2;
        or_cond_reg_1394 <= or_cond_fu_491_p2;
        tmp10_reg_1434 <= tmp10_fu_523_p2;
        tmp11_reg_1439 <= tmp11_fu_528_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (ap_const_lv1_0 == exitcond_reg_1385) & ~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_156 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it10))))) begin
        or_cond3_reg_1459 <= or_cond3_fu_569_p2;
        pix_val_2_reg_1453 <= line_buffer_0_2_val_q0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        row_1_reg_1360 <= row_1_fu_437_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_156 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it10))) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_1385_pp0_it2))) begin
        tmp4_reg_1520[1] <= tmp4_fu_703_p2[1];
tmp4_reg_1520[2] <= tmp4_fu_703_p2[2];
tmp4_reg_1520[3] <= tmp4_fu_703_p2[3];
tmp4_reg_1520[4] <= tmp4_fu_703_p2[4];
tmp4_reg_1520[5] <= tmp4_fu_703_p2[5];
tmp4_reg_1520[6] <= tmp4_fu_703_p2[6];
tmp4_reg_1520[7] <= tmp4_fu_703_p2[7];
tmp4_reg_1520[8] <= tmp4_fu_703_p2[8];
tmp4_reg_1520[9] <= tmp4_fu_703_p2[9];
        tmp_6_i2_reg_1525[1] <= tmp_6_i2_fu_741_p2[1];
tmp_6_i2_reg_1525[2] <= tmp_6_i2_fu_741_p2[2];
tmp_6_i2_reg_1525[3] <= tmp_6_i2_fu_741_p2[3];
tmp_6_i2_reg_1525[4] <= tmp_6_i2_fu_741_p2[4];
tmp_6_i2_reg_1525[5] <= tmp_6_i2_fu_741_p2[5];
tmp_6_i2_reg_1525[6] <= tmp_6_i2_fu_741_p2[6];
tmp_6_i2_reg_1525[7] <= tmp_6_i2_fu_741_p2[7];
tmp_6_i2_reg_1525[8] <= tmp_6_i2_fu_741_p2[8];
tmp_6_i2_reg_1525[9] <= tmp_6_i2_fu_741_p2[9];
tmp_6_i2_reg_1525[10] <= tmp_6_i2_fu_741_p2[10];
tmp_6_i2_reg_1525[11] <= tmp_6_i2_fu_741_p2[11];
tmp_6_i2_reg_1525[12] <= tmp_6_i2_fu_741_p2[12];
tmp_6_i2_reg_1525[13] <= tmp_6_i2_fu_741_p2[13];
tmp_6_i2_reg_1525[14] <= tmp_6_i2_fu_741_p2[14];
        tmp_i_reg_1515 <= {{tmp_8_i_fu_676_p2[ap_const_lv32_F : ap_const_lv32_8]}};
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & (exitcond1_fu_432_p2 == ap_const_lv1_0))) begin
        tmp_11_reg_1365 <= tmp_11_fu_443_p2;
        tmp_12_reg_1370 <= tmp_12_fu_454_p2;
        tmp_13_reg_1375 <= tmp_13_fu_460_p2;
        tmp_s_reg_1380 <= tmp_s_fu_466_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_156 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it10))) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_1385_pp0_it7) & (ap_const_lv1_0 == ap_reg_ppstg_or_cond3_reg_1459_pp0_it7))) begin
        tmp_15_i_reg_1606 <= tmp_15_i_fu_1143_p2;
        tmp_17_i_reg_1612 <= tmp_17_i_fu_1148_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_156 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it10))) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_1385_pp0_it5) & (ap_const_lv1_0 == ap_reg_ppstg_or_cond3_reg_1459_pp0_it5))) begin
        tmp_28_reg_1582 <= tmp_28_fu_1057_p1;
        tmp_29_reg_1588 <= tmp_29_fu_1061_p1;
        x_weight_2_2_2_i_reg_1572 <= x_weight_2_2_2_i_fu_1045_p2;
        y_weight_2_2_2_i_reg_1577 <= y_weight_2_2_2_i_fu_1051_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_156 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it10))) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_1385_pp0_it3))) begin
        tmp_2_i3_reg_1551 <= tmp_2_i3_fu_880_p2;
        tmp_i1_reg_1541 <= {{tmp_8_i1_fu_809_p2[ap_const_lv32_F : ap_const_lv32_8]}};
        tmp_i2_reg_1546 <= {{tmp_8_i2_fu_858_p2[ap_const_lv32_F : ap_const_lv32_8]}};
        y_window_2_1_2_reg_1536 <= y_window_2_1_2_fu_750_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_156 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it10))) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_1385_pp0_it4) & (ap_const_lv1_0 == ap_reg_ppstg_or_cond3_reg_1459_pp0_it4))) begin
        x_weight_2_0_2_i_reg_1562 <= x_weight_2_0_2_i_fu_927_p2;
        y_weight_2_1_2_i_reg_1567 <= y_weight_2_1_2_i_fu_943_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it5) & ~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_156 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it10))) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_1385_pp0_it4))) begin
        y_window_0_1_fu_160 <= y_window_0_1_1_fu_896_p2;
        y_window_0_2_fu_164 <= y_window_0_1_fu_160;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_156 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it10))) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_1385_pp0_it4))) begin
        y_window_1_1_1_reg_1556 <= y_window_1_1_1_fu_891_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it6) & ~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_156 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it10))) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_1385_pp0_it5))) begin
        y_window_1_1_fu_172 <= y_window_1_1_1_reg_1556;
        y_window_1_2_fu_176 <= y_window_1_1_fu_172;
        y_window_2_2_fu_180 <= ap_reg_ppstg_y_window_2_2_1_reg_1530_pp0_it5;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it4) & ~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_156 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it10))) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_1385_pp0_it3))) begin
        y_window_2_1_fu_184 <= y_window_2_1_2_fu_750_p2;
    end
end

/// ap_done assign process. ///
always @ (ap_done_reg or exitcond1_fu_432_p2 or ap_sig_cseq_ST_st2_fsm_1)
begin
    if (((ap_const_logic_1 == ap_done_reg) | ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & ~(exitcond1_fu_432_p2 == ap_const_lv1_0)))) begin
        ap_done = ap_const_logic_1;
    end else begin
        ap_done = ap_const_logic_0;
    end
end

/// ap_idle assign process. ///
always @ (ap_start or ap_sig_cseq_ST_st1_fsm_0)
begin
    if ((~(ap_const_logic_1 == ap_start) & (ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0))) begin
        ap_idle = ap_const_logic_1;
    end else begin
        ap_idle = ap_const_logic_0;
    end
end

/// ap_ready assign process. ///
always @ (exitcond1_fu_432_p2 or ap_sig_cseq_ST_st2_fsm_1)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & ~(exitcond1_fu_432_p2 == ap_const_lv1_0))) begin
        ap_ready = ap_const_logic_1;
    end else begin
        ap_ready = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_pp0_stg0_fsm_2 assign process. ///
always @ (ap_sig_bdd_107)
begin
    if (ap_sig_bdd_107) begin
        ap_sig_cseq_ST_pp0_stg0_fsm_2 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_pp0_stg0_fsm_2 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st14_fsm_3 assign process. ///
always @ (ap_sig_bdd_429)
begin
    if (ap_sig_bdd_429) begin
        ap_sig_cseq_ST_st14_fsm_3 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st14_fsm_3 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st1_fsm_0 assign process. ///
always @ (ap_sig_bdd_23)
begin
    if (ap_sig_bdd_23) begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st2_fsm_1 assign process. ///
always @ (ap_sig_bdd_85)
begin
    if (ap_sig_bdd_85) begin
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    end
end

/// grp_fu_1137_ce assign process. ///
always @ (ap_sig_cseq_ST_pp0_stg0_fsm_2 or ap_sig_bdd_124 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_156 or ap_reg_ppiten_pp0_it10)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_156 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it10))))) begin
        grp_fu_1137_ce = ap_const_logic_1;
    end else begin
        grp_fu_1137_ce = ap_const_logic_0;
    end
end

/// grp_fu_563_ce assign process. ///
always @ (exitcond_reg_1385 or ap_sig_cseq_ST_pp0_stg0_fsm_2 or ap_sig_bdd_124 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_156 or ap_reg_ppiten_pp0_it10 or ap_reg_ppstg_exitcond_reg_1385_pp0_it1 or ap_reg_ppstg_exitcond_reg_1385_pp0_it2)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_156 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it10))) & ((ap_const_lv1_0 == exitcond_reg_1385) | (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_1385_pp0_it1) | (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_1385_pp0_it2)))) begin
        grp_fu_563_ce = ap_const_logic_1;
    end else begin
        grp_fu_563_ce = ap_const_logic_0;
    end
end

/// grp_fu_606_ce assign process. ///
always @ (ap_sig_cseq_ST_pp0_stg0_fsm_2 or ap_sig_bdd_124 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_156 or ap_reg_ppiten_pp0_it10 or ap_reg_ppstg_exitcond_reg_1385_pp0_it1 or ap_reg_ppstg_exitcond_reg_1385_pp0_it2 or ap_reg_ppstg_exitcond_reg_1385_pp0_it3)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_156 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it10))) & ((ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_1385_pp0_it1) | (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_1385_pp0_it2) | (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_1385_pp0_it3)))) begin
        grp_fu_606_ce = ap_const_logic_1;
    end else begin
        grp_fu_606_ce = ap_const_logic_0;
    end
end

/// grp_fu_616_ce assign process. ///
always @ (ap_sig_cseq_ST_pp0_stg0_fsm_2 or ap_sig_bdd_124 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_156 or ap_reg_ppiten_pp0_it10 or ap_reg_ppstg_exitcond_reg_1385_pp0_it1 or ap_reg_ppstg_exitcond_reg_1385_pp0_it2 or ap_reg_ppstg_exitcond_reg_1385_pp0_it3)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_156 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it10))) & ((ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_1385_pp0_it1) | (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_1385_pp0_it2) | (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_1385_pp0_it3)))) begin
        grp_fu_616_ce = ap_const_logic_1;
    end else begin
        grp_fu_616_ce = ap_const_logic_0;
    end
end

/// img_0_data_stream_0_V_read assign process. ///
always @ (exitcond_reg_1385 or ap_sig_cseq_ST_pp0_stg0_fsm_2 or or_cond_reg_1394 or ap_sig_bdd_124 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_156 or ap_reg_ppiten_pp0_it10)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (ap_const_lv1_0 == exitcond_reg_1385) & ~(ap_const_lv1_0 == or_cond_reg_1394) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_156 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it10))))) begin
        img_0_data_stream_0_V_read = ap_const_logic_1;
    end else begin
        img_0_data_stream_0_V_read = ap_const_logic_0;
    end
end

/// img_0_data_stream_1_V_read assign process. ///
always @ (exitcond_reg_1385 or ap_sig_cseq_ST_pp0_stg0_fsm_2 or or_cond_reg_1394 or ap_sig_bdd_124 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_156 or ap_reg_ppiten_pp0_it10)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (ap_const_lv1_0 == exitcond_reg_1385) & ~(ap_const_lv1_0 == or_cond_reg_1394) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_156 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it10))))) begin
        img_0_data_stream_1_V_read = ap_const_logic_1;
    end else begin
        img_0_data_stream_1_V_read = ap_const_logic_0;
    end
end

/// img_0_data_stream_2_V_read assign process. ///
always @ (exitcond_reg_1385 or ap_sig_cseq_ST_pp0_stg0_fsm_2 or or_cond_reg_1394 or ap_sig_bdd_124 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_156 or ap_reg_ppiten_pp0_it10)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (ap_const_lv1_0 == exitcond_reg_1385) & ~(ap_const_lv1_0 == or_cond_reg_1394) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_156 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it10))))) begin
        img_0_data_stream_2_V_read = ap_const_logic_1;
    end else begin
        img_0_data_stream_2_V_read = ap_const_logic_0;
    end
end

/// img_1_data_stream_0_V_write assign process. ///
always @ (ap_sig_bdd_124 or ap_reg_ppiten_pp0_it1 or ap_reg_ppstg_or_cond2_reg_1444_pp0_it9 or ap_sig_bdd_156 or ap_reg_ppiten_pp0_it10)
begin
    if ((~(ap_const_lv1_0 == ap_reg_ppstg_or_cond2_reg_1444_pp0_it9) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it10) & ~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_156 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it10))))) begin
        img_1_data_stream_0_V_write = ap_const_logic_1;
    end else begin
        img_1_data_stream_0_V_write = ap_const_logic_0;
    end
end

/// img_1_data_stream_1_V_write assign process. ///
always @ (ap_sig_bdd_124 or ap_reg_ppiten_pp0_it1 or ap_reg_ppstg_or_cond2_reg_1444_pp0_it9 or ap_sig_bdd_156 or ap_reg_ppiten_pp0_it10)
begin
    if ((~(ap_const_lv1_0 == ap_reg_ppstg_or_cond2_reg_1444_pp0_it9) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it10) & ~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_156 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it10))))) begin
        img_1_data_stream_1_V_write = ap_const_logic_1;
    end else begin
        img_1_data_stream_1_V_write = ap_const_logic_0;
    end
end

/// img_1_data_stream_2_V_write assign process. ///
always @ (ap_sig_bdd_124 or ap_reg_ppiten_pp0_it1 or ap_reg_ppstg_or_cond2_reg_1444_pp0_it9 or ap_sig_bdd_156 or ap_reg_ppiten_pp0_it10)
begin
    if ((~(ap_const_lv1_0 == ap_reg_ppstg_or_cond2_reg_1444_pp0_it9) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it10) & ~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_156 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it10))))) begin
        img_1_data_stream_2_V_write = ap_const_logic_1;
    end else begin
        img_1_data_stream_2_V_write = ap_const_logic_0;
    end
end

/// line_buffer_0_0_val_ce0 assign process. ///
always @ (ap_sig_cseq_ST_pp0_stg0_fsm_2 or ap_sig_bdd_124 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_156 or ap_reg_ppiten_pp0_it10)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_156 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it10))))) begin
        line_buffer_0_0_val_ce0 = ap_const_logic_1;
    end else begin
        line_buffer_0_0_val_ce0 = ap_const_logic_0;
    end
end

/// line_buffer_0_0_val_ce1 assign process. ///
always @ (ap_sig_bdd_124 or ap_reg_ppiten_pp0_it1 or ap_reg_ppiten_pp0_it2 or ap_sig_bdd_156 or ap_reg_ppiten_pp0_it10)
begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_156 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it10))))) begin
        line_buffer_0_0_val_ce1 = ap_const_logic_1;
    end else begin
        line_buffer_0_0_val_ce1 = ap_const_logic_0;
    end
end

/// line_buffer_0_0_val_we1 assign process. ///
always @ (ap_sig_bdd_124 or ap_reg_ppiten_pp0_it1 or ap_reg_ppiten_pp0_it2 or ap_sig_bdd_156 or ap_reg_ppiten_pp0_it10 or ap_reg_ppstg_exitcond_reg_1385_pp0_it1)
begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_156 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it10))) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_1385_pp0_it1))) begin
        line_buffer_0_0_val_we1 = ap_const_logic_1;
    end else begin
        line_buffer_0_0_val_we1 = ap_const_logic_0;
    end
end

/// line_buffer_0_1_val_ce0 assign process. ///
always @ (ap_sig_cseq_ST_pp0_stg0_fsm_2 or ap_sig_bdd_124 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_156 or ap_reg_ppiten_pp0_it10)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_156 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it10))))) begin
        line_buffer_0_1_val_ce0 = ap_const_logic_1;
    end else begin
        line_buffer_0_1_val_ce0 = ap_const_logic_0;
    end
end

/// line_buffer_0_1_val_ce1 assign process. ///
always @ (ap_sig_bdd_124 or ap_reg_ppiten_pp0_it1 or ap_reg_ppiten_pp0_it2 or ap_sig_bdd_156 or ap_reg_ppiten_pp0_it10)
begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_156 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it10))))) begin
        line_buffer_0_1_val_ce1 = ap_const_logic_1;
    end else begin
        line_buffer_0_1_val_ce1 = ap_const_logic_0;
    end
end

/// line_buffer_0_1_val_we1 assign process. ///
always @ (ap_sig_bdd_124 or ap_reg_ppiten_pp0_it1 or ap_reg_ppiten_pp0_it2 or ap_sig_bdd_156 or ap_reg_ppiten_pp0_it10 or ap_reg_ppstg_exitcond_reg_1385_pp0_it1)
begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_156 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it10))) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_1385_pp0_it1))) begin
        line_buffer_0_1_val_we1 = ap_const_logic_1;
    end else begin
        line_buffer_0_1_val_we1 = ap_const_logic_0;
    end
end

/// line_buffer_0_2_val_ce0 assign process. ///
always @ (ap_sig_cseq_ST_pp0_stg0_fsm_2 or ap_reg_ppiten_pp0_it0 or ap_sig_bdd_124 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_156 or ap_reg_ppiten_pp0_it10)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_156 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it10))))) begin
        line_buffer_0_2_val_ce0 = ap_const_logic_1;
    end else begin
        line_buffer_0_2_val_ce0 = ap_const_logic_0;
    end
end

/// line_buffer_0_2_val_ce1 assign process. ///
always @ (ap_sig_bdd_124 or ap_reg_ppiten_pp0_it1 or ap_reg_ppiten_pp0_it2 or ap_sig_bdd_156 or ap_reg_ppiten_pp0_it10)
begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_156 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it10))))) begin
        line_buffer_0_2_val_ce1 = ap_const_logic_1;
    end else begin
        line_buffer_0_2_val_ce1 = ap_const_logic_0;
    end
end

/// line_buffer_0_2_val_we1 assign process. ///
always @ (ap_sig_bdd_124 or ap_reg_ppiten_pp0_it1 or ap_reg_ppiten_pp0_it2 or ap_sig_bdd_156 or ap_reg_ppiten_pp0_it10 or ap_reg_ppstg_exitcond_reg_1385_pp0_it1)
begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_156 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it10))) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_1385_pp0_it1))) begin
        line_buffer_0_2_val_we1 = ap_const_logic_1;
    end else begin
        line_buffer_0_2_val_we1 = ap_const_logic_0;
    end
end

/// line_buffer_1_0_val_ce0 assign process. ///
always @ (ap_sig_cseq_ST_pp0_stg0_fsm_2 or ap_sig_bdd_124 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_156 or ap_reg_ppiten_pp0_it10)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_156 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it10))))) begin
        line_buffer_1_0_val_ce0 = ap_const_logic_1;
    end else begin
        line_buffer_1_0_val_ce0 = ap_const_logic_0;
    end
end

/// line_buffer_1_0_val_ce1 assign process. ///
always @ (ap_sig_bdd_124 or ap_reg_ppiten_pp0_it1 or ap_reg_ppiten_pp0_it2 or ap_sig_bdd_156 or ap_reg_ppiten_pp0_it10)
begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_156 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it10))))) begin
        line_buffer_1_0_val_ce1 = ap_const_logic_1;
    end else begin
        line_buffer_1_0_val_ce1 = ap_const_logic_0;
    end
end

/// line_buffer_1_0_val_we1 assign process. ///
always @ (ap_sig_bdd_124 or ap_reg_ppiten_pp0_it1 or ap_reg_ppiten_pp0_it2 or ap_sig_bdd_156 or ap_reg_ppiten_pp0_it10 or ap_reg_ppstg_exitcond_reg_1385_pp0_it1)
begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_156 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it10))) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_1385_pp0_it1))) begin
        line_buffer_1_0_val_we1 = ap_const_logic_1;
    end else begin
        line_buffer_1_0_val_we1 = ap_const_logic_0;
    end
end

/// line_buffer_1_1_val_ce0 assign process. ///
always @ (ap_sig_cseq_ST_pp0_stg0_fsm_2 or ap_sig_bdd_124 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_156 or ap_reg_ppiten_pp0_it10)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_156 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it10))))) begin
        line_buffer_1_1_val_ce0 = ap_const_logic_1;
    end else begin
        line_buffer_1_1_val_ce0 = ap_const_logic_0;
    end
end

/// line_buffer_1_1_val_ce1 assign process. ///
always @ (ap_sig_bdd_124 or ap_reg_ppiten_pp0_it1 or ap_reg_ppiten_pp0_it2 or ap_sig_bdd_156 or ap_reg_ppiten_pp0_it10)
begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_156 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it10))))) begin
        line_buffer_1_1_val_ce1 = ap_const_logic_1;
    end else begin
        line_buffer_1_1_val_ce1 = ap_const_logic_0;
    end
end

/// line_buffer_1_1_val_we1 assign process. ///
always @ (ap_sig_bdd_124 or ap_reg_ppiten_pp0_it1 or ap_reg_ppiten_pp0_it2 or ap_sig_bdd_156 or ap_reg_ppiten_pp0_it10 or ap_reg_ppstg_exitcond_reg_1385_pp0_it1)
begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_156 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it10))) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_1385_pp0_it1))) begin
        line_buffer_1_1_val_we1 = ap_const_logic_1;
    end else begin
        line_buffer_1_1_val_we1 = ap_const_logic_0;
    end
end

/// line_buffer_1_2_val_ce0 assign process. ///
always @ (ap_sig_cseq_ST_pp0_stg0_fsm_2 or ap_reg_ppiten_pp0_it0 or ap_sig_bdd_124 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_156 or ap_reg_ppiten_pp0_it10)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_156 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it10))))) begin
        line_buffer_1_2_val_ce0 = ap_const_logic_1;
    end else begin
        line_buffer_1_2_val_ce0 = ap_const_logic_0;
    end
end

/// line_buffer_1_2_val_ce1 assign process. ///
always @ (ap_sig_cseq_ST_pp0_stg0_fsm_2 or ap_sig_bdd_124 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_156 or ap_reg_ppiten_pp0_it10)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_156 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it10))))) begin
        line_buffer_1_2_val_ce1 = ap_const_logic_1;
    end else begin
        line_buffer_1_2_val_ce1 = ap_const_logic_0;
    end
end

/// line_buffer_1_2_val_we1 assign process. ///
always @ (exitcond_reg_1385 or ap_sig_cseq_ST_pp0_stg0_fsm_2 or ap_sig_bdd_124 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_156 or ap_reg_ppiten_pp0_it10)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (ap_const_lv1_0 == exitcond_reg_1385) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_156 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it10))))) begin
        line_buffer_1_2_val_we1 = ap_const_logic_1;
    end else begin
        line_buffer_1_2_val_we1 = ap_const_logic_0;
    end
end
/// the next state (ap_NS_fsm) of the state machine. ///
always @ (ap_CS_fsm or ap_sig_bdd_65 or exitcond1_fu_432_p2 or ap_sig_bdd_124 or ap_reg_ppiten_pp0_it1 or ap_reg_ppiten_pp0_it3 or ap_reg_ppiten_pp0_it4 or ap_reg_ppiten_pp0_it5 or ap_reg_ppiten_pp0_it9 or ap_sig_bdd_156 or ap_reg_ppiten_pp0_it10)
begin
    case (ap_CS_fsm)
        ap_ST_st1_fsm_0 : 
        begin
            if (~ap_sig_bdd_65) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end
        end
        ap_ST_st2_fsm_1 : 
        begin
            if (~(exitcond1_fu_432_p2 == ap_const_lv1_0)) begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end else begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_2;
            end
        end
        ap_ST_pp0_stg0_fsm_2 : 
        begin
            if ((~((ap_const_logic_1 == ap_reg_ppiten_pp0_it10) & ~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_156 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it10))) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it9)) & ~((ap_const_logic_1 == ap_reg_ppiten_pp0_it4) & ~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_156 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it10))) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it3) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it5)))) begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_2;
            end else if ((((ap_const_logic_1 == ap_reg_ppiten_pp0_it10) & ~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_156 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it10))) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it9)) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it4) & ~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_156 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it10))) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it3) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it5)))) begin
                ap_NS_fsm = ap_ST_st14_fsm_3;
            end else begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_2;
            end
        end
        ap_ST_st14_fsm_3 : 
        begin
            ap_NS_fsm = ap_ST_st2_fsm_1;
        end
        default : 
        begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign G_3_fu_1208_p2 = (B_cast_i_reg_1617 + ap_const_lv9_22);
assign R_3_fu_1203_p2 = (B_cast_i_reg_1617 + ap_const_lv9_3C);
assign ap_reg_phiprechg_edge_val1_reg_368pp0_it1 = 'bx;

/// ap_sig_bdd_107 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_107 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_2]);
end

/// ap_sig_bdd_124 assign process. ///
always @ (img_0_data_stream_0_V_empty_n or img_0_data_stream_1_V_empty_n or img_0_data_stream_2_V_empty_n or exitcond_reg_1385 or or_cond_reg_1394)
begin
    ap_sig_bdd_124 = (((img_0_data_stream_0_V_empty_n == ap_const_logic_0) & (ap_const_lv1_0 == exitcond_reg_1385) & ~(ap_const_lv1_0 == or_cond_reg_1394)) | ((ap_const_lv1_0 == exitcond_reg_1385) & ~(ap_const_lv1_0 == or_cond_reg_1394) & (img_0_data_stream_1_V_empty_n == ap_const_logic_0)) | ((ap_const_lv1_0 == exitcond_reg_1385) & ~(ap_const_lv1_0 == or_cond_reg_1394) & (img_0_data_stream_2_V_empty_n == ap_const_logic_0)));
end

/// ap_sig_bdd_156 assign process. ///
always @ (img_1_data_stream_0_V_full_n or img_1_data_stream_1_V_full_n or img_1_data_stream_2_V_full_n or ap_reg_ppstg_or_cond2_reg_1444_pp0_it9)
begin
    ap_sig_bdd_156 = (((img_1_data_stream_0_V_full_n == ap_const_logic_0) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond2_reg_1444_pp0_it9)) | (~(ap_const_lv1_0 == ap_reg_ppstg_or_cond2_reg_1444_pp0_it9) & (img_1_data_stream_1_V_full_n == ap_const_logic_0)) | (~(ap_const_lv1_0 == ap_reg_ppstg_or_cond2_reg_1444_pp0_it9) & (img_1_data_stream_2_V_full_n == ap_const_logic_0)));
end

/// ap_sig_bdd_23 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_23 = (ap_CS_fsm[ap_const_lv32_0] == ap_const_lv1_1);
end

/// ap_sig_bdd_349 assign process. ///
always @ (ap_reg_ppstg_exitcond_reg_1385_pp0_it8 or ap_reg_ppstg_or_cond3_reg_1459_pp0_it8)
begin
    ap_sig_bdd_349 = ((ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_1385_pp0_it8) & (ap_const_lv1_0 == ap_reg_ppstg_or_cond3_reg_1459_pp0_it8));
end

/// ap_sig_bdd_429 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_429 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_3]);
end

/// ap_sig_bdd_436 assign process. ///
always @ (ap_sig_bdd_124 or ap_reg_ppiten_pp0_it1 or ap_reg_ppiten_pp0_it9 or ap_sig_bdd_156 or ap_reg_ppiten_pp0_it10)
begin
    ap_sig_bdd_436 = ((ap_const_logic_1 == ap_reg_ppiten_pp0_it9) & ~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_156 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it10))));
end

/// ap_sig_bdd_444 assign process. ///
always @ (ap_sig_cseq_ST_pp0_stg0_fsm_2 or ap_sig_bdd_124 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_156 or ap_reg_ppiten_pp0_it10)
begin
    ap_sig_bdd_444 = ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_156 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it10))));
end

/// ap_sig_bdd_459 assign process. ///
always @ (exitcond_reg_1385 or or_cond3_fu_569_p2)
begin
    ap_sig_bdd_459 = ((ap_const_lv1_0 == exitcond_reg_1385) & ~(ap_const_lv1_0 == or_cond3_fu_569_p2));
end

/// ap_sig_bdd_65 assign process. ///
always @ (ap_start or ap_done_reg)
begin
    ap_sig_bdd_65 = ((ap_start == ap_const_logic_0) | (ap_done_reg == ap_const_logic_1));
end

/// ap_sig_bdd_85 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_85 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_1]);
end
assign col_1_fu_476_p2 = (col_reg_357 + ap_const_lv11_1);
assign col_cast_fu_482_p1 = col_reg_357;
assign edge_val_1_fu_1195_p3 = ((tmp_27_fu_1191_p2)? p_i_cast_fu_1183_p3: edge_val_fu_1173_p2);
assign edge_val_fu_1173_p2 = (ap_reg_ppstg_edge_weight_i_reg_1594_pp0_it8 ^ ap_const_lv8_FF);
assign edge_weight_i_fu_1115_p2 = (tmp_26_fu_1108_p3 + tmp_23_fu_1091_p3);
assign exitcond1_fu_432_p2 = (row_reg_346 == tmp_10_fu_414_p2? 1'b1: 1'b0);
assign exitcond_fu_471_p2 = (col_reg_357 == tmp_9_fu_408_p2? 1'b1: 1'b0);
assign grp_fu_1137_p0 = grp_fu_1137_p00;
assign grp_fu_1137_p00 = tmp_3_i_fu_1127_p2;
assign grp_fu_1137_p1 = ap_const_lv22_556;
assign grp_fu_563_p0 = grp_fu_563_p00;
assign grp_fu_563_p00 = line_buffer_1_2_val_q0;
assign grp_fu_563_p1 = ap_const_lv13_19;
assign grp_fu_606_p0 = grp_fu_606_p00;
assign grp_fu_606_p00 = pix_val_2_reg_1453;
assign grp_fu_606_p1 = ap_const_lv13_19;
assign grp_fu_616_p0 = grp_fu_616_p00;
assign grp_fu_616_p00 = B_2_fu_152;
assign grp_fu_616_p1 = ap_const_lv13_19;
assign img_1_data_stream_0_V_din = (ap_reg_ppstg_sepia_val_0_reg_1623_pp0_it9 + ap_reg_phiprechg_edge_val1_reg_368pp0_it10);
assign img_1_data_stream_1_V_din = (sepia_val_1_reg_1638 + ap_reg_phiprechg_edge_val1_reg_368pp0_it10);
assign img_1_data_stream_2_V_din = (sepia_val_2_reg_1633 + ap_reg_phiprechg_edge_val1_reg_368pp0_it10);
assign line_buffer_0_0_val_address0 = line_buffer_0_0_val_addr_reg_1416;
assign line_buffer_0_0_val_address1 = ap_reg_ppstg_line_buffer_0_0_val_addr_reg_1416_pp0_it1;
assign line_buffer_0_0_val_d1 = R_2_fu_168;
assign line_buffer_0_1_val_address0 = line_buffer_0_1_val_addr_reg_1422;
assign line_buffer_0_1_val_address1 = ap_reg_ppstg_line_buffer_0_1_val_addr_reg_1422_pp0_it1;
assign line_buffer_0_1_val_d1 = G_2_fu_156;
assign line_buffer_0_2_val_address0 = tmp_16_fu_496_p1;
assign line_buffer_0_2_val_address1 = ap_reg_ppstg_line_buffer_0_2_val_addr_reg_1428_pp0_it1;
assign line_buffer_0_2_val_d1 = B_2_fu_152;
assign line_buffer_1_0_val_address0 = line_buffer_1_0_val_addr_reg_1398;
assign line_buffer_1_0_val_address1 = ap_reg_ppstg_line_buffer_1_0_val_addr_reg_1398_pp0_it1;
assign line_buffer_1_0_val_d1 = line_buffer_0_0_val_q0;
assign line_buffer_1_1_val_address0 = line_buffer_1_1_val_addr_reg_1404;
assign line_buffer_1_1_val_address1 = ap_reg_ppstg_line_buffer_1_1_val_addr_reg_1404_pp0_it1;
assign line_buffer_1_1_val_d1 = line_buffer_0_1_val_q0;
assign line_buffer_1_2_val_address0 = tmp_16_fu_496_p1;
assign line_buffer_1_2_val_address1 = line_buffer_1_2_val_addr_reg_1410;
assign line_buffer_1_2_val_d1 = line_buffer_0_2_val_q0;
assign not_tmp_15_i_fu_1178_p2 = (tmp_15_i_reg_1606 ^ ap_const_lv1_1);
assign or_cond2_fu_539_p2 = (tmp_13_reg_1375 & tmp_19_fu_533_p2);
assign or_cond3_fu_569_p2 = (tmp11_reg_1439 | tmp10_reg_1434);
assign or_cond_fu_491_p2 = (tmp_11_reg_1365 & tmp_14_fu_486_p2);
assign output_col_fu_506_p2 = ($signed(col_cast_fu_482_p1) + $signed(ap_const_lv12_FFF));
assign output_row_fu_448_p2 = ($signed(row_cast_fu_428_p1) + $signed(ap_const_lv12_FFF));
assign p_i_cast_fu_1183_p3 = ((not_tmp_15_i_fu_1178_p2)? ap_const_lv8_FF: ap_const_lv8_0);
assign p_shl1_cast_i1_fu_716_p1 = p_shl1_i1_fu_709_p3;
assign p_shl1_cast_i5_fu_762_p1 = p_shl1_i4_fu_755_p3;
assign p_shl1_cast_i_fu_629_p1 = p_shl1_i_fu_622_p3;
assign p_shl1_i1_fu_709_p3 = {{R_5_reg_1469}, {ap_const_lv6_0}};
assign p_shl1_i4_fu_755_p3 = {{ap_reg_ppstg_pix_val_0_reg_1491_pp0_it3}, {ap_const_lv6_0}};
assign p_shl1_i_fu_622_p3 = {{R_reg_1475}, {ap_const_lv6_0}};
assign p_shl2_cast_i29_cast_fu_727_p1 = p_shl2_i1_fu_720_p3;
assign p_shl2_cast_i7_cast_fu_699_p1 = p_shl2_i6_fu_692_p3;
assign p_shl2_cast_i_cast_fu_593_p1 = p_shl2_i_fu_585_p3;
assign p_shl2_i1_fu_720_p3 = {{R_5_reg_1469}, {ap_const_lv1_0}};
assign p_shl2_i6_fu_692_p3 = {{pix_val_0_reg_1491}, {ap_const_lv1_0}};
assign p_shl2_i_fu_585_p3 = {{line_buffer_1_0_val_q0}, {ap_const_lv1_0}};
assign p_shl8_cast_i_fu_978_p1 = p_shl8_i_fu_971_p3;
assign p_shl8_i_fu_971_p3 = {{y_window_1_1_1_reg_1556}, {ap_const_lv1_0}};
assign p_shl_cast_i1_fu_776_p1 = p_shl_i1_fu_769_p3;
assign p_shl_cast_i2_fu_835_p1 = p_shl_i2_fu_828_p3;
assign p_shl_cast_i3_fu_1031_p1 = p_shl_i3_fu_1024_p3;
assign p_shl_cast_i_fu_643_p1 = p_shl_i_fu_636_p3;
assign p_shl_i1_fu_769_p3 = {{ap_reg_ppstg_pix_val_1_reg_1498_pp0_it3}, {ap_const_lv7_0}};
assign p_shl_i2_fu_828_p3 = {{ap_reg_ppstg_G_5_reg_1463_pp0_it3}, {ap_const_lv7_0}};
assign p_shl_i3_fu_1024_p3 = {{ap_reg_ppstg_y_window_2_2_1_reg_1530_pp0_it5}, {ap_const_lv1_0}};
assign p_shl_i_fu_636_p3 = {{G_reg_1480}, {ap_const_lv7_0}};
assign row_1_fu_437_p2 = (row_reg_346 + ap_const_lv11_1);
assign row_cast_fu_428_p1 = row_reg_346;
assign sepia_val_1_fu_1245_p3 = ((tmp_32_fu_1233_p3)? ap_const_lv8_FF: tmp_33_fu_1241_p1);
assign sepia_val_2_fu_1225_p3 = ((tmp_30_fu_1213_p3)? ap_const_lv8_FF: tmp_31_fu_1221_p1);
assign tmp10_fu_523_p2 = (tmp_12_reg_1370 | tmp_17_fu_512_p2);
assign tmp11_fu_528_p2 = (tmp_s_reg_1380 | tmp_18_fu_518_p2);
assign tmp12_fu_933_p2 = (tmp_19_0_cast9_i_cast_fu_907_p1 + tmp_19_0_2_cast8_i_cast_fu_923_p1);
assign tmp1_fu_597_p2 = (p_shl2_cast_i_cast_fu_593_p1 + ap_const_lv10_80);
assign tmp2_fu_660_p2 = (p_shl_cast_i_fu_643_p1 + tmp_6_cast_i_fu_656_p1);
assign tmp3_fu_666_p2 = (grp_fu_563_p2 + tmp_2_cast3_i_cast_fu_633_p1);
assign tmp4_fu_703_p2 = (p_shl2_cast_i7_cast_fu_699_p1 + ap_const_lv10_80);
assign tmp55_cast_fu_647_p1 = tmp1_reg_1486;
assign tmp57_cast_fu_672_p1 = tmp3_fu_666_p2;
assign tmp58_cast_fu_780_p1 = tmp4_reg_1520;
assign tmp5_fu_793_p2 = (p_shl_cast_i1_fu_776_p1 + tmp_6_cast_i1_fu_789_p1);
assign tmp60_cast_fu_805_p1 = tmp6_fu_799_p2;
assign tmp61_cast_fu_737_p1 = tmp7_fu_731_p2;
assign tmp63_cast_fu_854_p1 = tmp9_fu_848_p2;
assign tmp66_cast_fu_939_p1 = tmp12_fu_933_p2;
assign tmp6_fu_799_p2 = (grp_fu_606_p2 + tmp_2_cast3_i9_cast_fu_766_p1);
assign tmp7_fu_731_p2 = (p_shl2_cast_i29_cast_fu_727_p1 + ap_const_lv10_80);
assign tmp8_fu_842_p2 = (p_shl_cast_i2_fu_835_p1 + tmp_6_cast_i2_fu_839_p1);
assign tmp9_fu_848_p2 = (grp_fu_616_p2 + tmp_2_cast3_i31_cast_fu_825_p1);
assign tmp_10_fu_414_p2 = (tmp_fu_380_p1 + ap_const_lv11_1);
assign tmp_11_fu_443_p2 = ($signed(row_cast_fu_428_p1) < $signed(tmp_21_fu_420_p1)? 1'b1: 1'b0);
assign tmp_11_i_fu_1098_p2 = ($signed(y_weight_2_2_2_i_reg_1577) > $signed(11'b00000000000)? 1'b1: 1'b0);
assign tmp_12_fu_454_p2 = (output_row_fu_448_p2 == ap_const_lv12_0? 1'b1: 1'b0);
assign tmp_13_fu_460_p2 = (row_reg_346 != ap_const_lv11_0? 1'b1: 1'b0);
assign tmp_14_fu_486_p2 = ($signed(col_cast_fu_482_p1) < $signed(tmp_24_fu_424_p1)? 1'b1: 1'b0);
assign tmp_15_cast_fu_390_p1 = tmp_7_fu_384_p2;
assign tmp_15_i_fu_1143_p2 = (edge_weight_i_reg_1594 < ap_const_lv8_37? 1'b1: 1'b0);
assign tmp_16_cast_fu_404_p1 = tmp_8_fu_398_p2;
assign tmp_16_fu_496_p1 = col_reg_357;
assign tmp_17_fu_512_p2 = (output_col_fu_506_p2 == ap_const_lv12_0? 1'b1: 1'b0);
assign tmp_17_i_fu_1148_p2 = (edge_weight_i_reg_1594 > ap_const_lv8_CD? 1'b1: 1'b0);
assign tmp_18_fu_518_p2 = (output_col_fu_506_p2 == tmp_16_cast_fu_404_p1? 1'b1: 1'b0);
assign tmp_19_0_2_cast8_i_cast_fu_923_p1 = y_window_0_2_fu_164;
assign tmp_19_0_cast9_i_cast_fu_907_p1 = y_window_0_1_1_fu_896_p2;
assign tmp_19_2_2_cast_i_fu_1041_p1 = y_window_2_2_fu_180;
assign tmp_19_2_cast_i_fu_1009_p1 = ap_reg_ppstg_y_window_2_1_2_reg_1536_pp0_it5;
assign tmp_19_fu_533_p2 = (col_reg_357 != ap_const_lv11_0? 1'b1: 1'b0);
assign tmp_1_cast_i_fu_1121_p1 = ap_reg_ppstg_pix_val_0_reg_1491_pp0_it6;
assign tmp_21_1_2_cast_i_fu_996_p1 = tmp_21_1_2_i_fu_988_p3;
assign tmp_21_1_2_i_fu_988_p3 = {{y_window_1_2_fu_176}, {ap_const_lv1_0}};
assign tmp_21_fu_420_p1 = rows[11:0];
assign tmp_22_fu_1086_p2 = (ap_const_lv8_0 - tmp_28_reg_1582);
assign tmp_23_0_1_cast_i_fu_919_p1 = tmp_23_0_1_i_fu_911_p3;
assign tmp_23_0_1_i_fu_911_p3 = {{y_window_0_1_fu_160}, {ap_const_lv1_0}};
assign tmp_23_fu_1091_p3 = ((tmp_i_29_fu_1081_p2)? tmp_28_reg_1582: tmp_22_fu_1086_p2);
assign tmp_24_fu_424_p1 = cols[11:0];
assign tmp_25_fu_1103_p2 = (ap_const_lv8_0 - tmp_29_reg_1588);
assign tmp_26_fu_1108_p3 = ((tmp_11_i_fu_1098_p2)? tmp_29_reg_1588: tmp_25_fu_1103_p2);
assign tmp_27_fu_1191_p2 = (tmp_15_i_reg_1606 | tmp_17_i_reg_1612);
assign tmp_28_fu_1057_p1 = x_weight_2_2_2_i_fu_1045_p2[7:0];
assign tmp_29_fu_1061_p1 = y_weight_2_2_2_i_fu_1051_p2[7:0];
assign tmp_2_cast3_i31_cast_fu_825_p1 = ap_reg_ppstg_G_5_reg_1463_pp0_it3;
assign tmp_2_cast3_i9_cast_fu_766_p1 = ap_reg_ppstg_pix_val_1_reg_1498_pp0_it3;
assign tmp_2_cast3_i_cast_fu_633_p1 = G_reg_1480;
assign tmp_2_cast_i3_fu_1124_p1 = ap_reg_ppstg_tmp_2_i3_reg_1551_pp0_it6;
assign tmp_2_fu_394_p1 = cols[10:0];
assign tmp_2_i3_fu_880_p2 = (tmp_cast_i_fu_877_p1 + tmp_cast_i2_fu_874_p1);
assign tmp_30_fu_1213_p3 = R_3_fu_1203_p2[ap_const_lv32_8];
assign tmp_31_fu_1221_p1 = R_3_fu_1203_p2[7:0];
assign tmp_32_fu_1233_p3 = G_3_fu_1208_p2[ap_const_lv32_8];
assign tmp_33_fu_1241_p1 = G_3_fu_1208_p2[7:0];
assign tmp_3_i_fu_1127_p2 = (tmp_2_cast_i3_fu_1124_p1 + tmp_1_cast_i_fu_1121_p1);
assign tmp_6_cast_i1_fu_789_p1 = tmp_6_i1_fu_783_p2;
assign tmp_6_cast_i2_fu_839_p1 = tmp_6_i2_reg_1525;
assign tmp_6_cast_i_fu_656_p1 = tmp_6_i_fu_650_p2;
assign tmp_6_i1_fu_783_p2 = (tmp58_cast_fu_780_p1 + p_shl1_cast_i5_fu_762_p1);
assign tmp_6_i2_fu_741_p2 = (tmp61_cast_fu_737_p1 + p_shl1_cast_i1_fu_716_p1);
assign tmp_6_i_fu_650_p2 = (tmp55_cast_fu_647_p1 + p_shl1_cast_i_fu_629_p1);
assign tmp_7_fu_384_p2 = ($signed(tmp_fu_380_p1) + $signed(ap_const_lv11_7FF));
assign tmp_8_fu_398_p2 = ($signed(tmp_2_fu_394_p1) + $signed(ap_const_lv11_7FF));
assign tmp_8_i1_fu_809_p2 = (tmp60_cast_fu_805_p1 + tmp5_fu_793_p2);
assign tmp_8_i2_fu_858_p2 = (tmp63_cast_fu_854_p1 + tmp8_fu_842_p2);
assign tmp_8_i_fu_676_p2 = (tmp57_cast_fu_672_p1 + tmp2_fu_660_p2);
assign tmp_9_fu_408_p2 = (tmp_2_fu_394_p1 + ap_const_lv11_1);
assign tmp_cast_i2_fu_874_p1 = ap_reg_ppstg_pix_val_2_reg_1453_pp0_it3;
assign tmp_cast_i_fu_877_p1 = ap_reg_ppstg_pix_val_1_reg_1498_pp0_it3;
assign tmp_fu_380_p1 = rows[10:0];
assign tmp_i_29_fu_1081_p2 = ($signed(x_weight_2_2_2_i_reg_1572) > $signed(11'b00000000000)? 1'b1: 1'b0);
assign tmp_s_fu_466_p2 = (output_row_fu_448_p2 == tmp_15_cast_fu_390_p1? 1'b1: 1'b0);
assign x_weight_2_0_2_cast_i_fu_968_p1 = $signed(x_weight_2_0_2_i_reg_1562);
assign x_weight_2_0_2_i_fu_927_p2 = (tmp_19_0_2_cast8_i_cast_fu_923_p1 - tmp_19_0_cast9_i_cast_fu_907_p1);
assign x_weight_2_1_1_i_fu_982_p2 = ($signed(x_weight_2_0_2_cast_i_fu_968_p1) - $signed(p_shl8_cast_i_fu_978_p1));
assign x_weight_2_1_2_i_fu_1000_p2 = ($signed(x_weight_2_1_1_i_fu_982_p2) + $signed(tmp_21_1_2_cast_i_fu_996_p1));
assign x_weight_2_2_2_i_fu_1045_p2 = ($signed(x_weight_2_2_i_fu_1012_p2) + $signed(tmp_19_2_2_cast_i_fu_1041_p1));
assign x_weight_2_2_i_fu_1012_p2 = ($signed(x_weight_2_1_2_i_fu_1000_p2) - $signed(tmp_19_2_cast_i_fu_1009_p1));
assign y_weight_2_1_2_cast_i_fu_1006_p1 = y_weight_2_1_2_i_reg_1567;
assign y_weight_2_1_2_i_fu_943_p2 = (tmp66_cast_fu_939_p1 + tmp_23_0_1_cast_i_fu_919_p1);
assign y_weight_2_2_1_i_fu_1035_p2 = (y_weight_2_2_i_fu_1018_p2 - p_shl_cast_i3_fu_1031_p1);
assign y_weight_2_2_2_i_fu_1051_p2 = (y_weight_2_2_1_i_fu_1035_p2 - tmp_19_2_2_cast_i_fu_1041_p1);
assign y_weight_2_2_i_fu_1018_p2 = (y_weight_2_1_2_cast_i_fu_1006_p1 - tmp_19_2_cast_i_fu_1009_p1);
assign y_window_0_1_1_fu_896_p2 = (tmp_i2_reg_1546 + ap_const_lv8_10);
assign y_window_1_1_1_fu_891_p2 = (tmp_i1_reg_1541 + ap_const_lv8_10);
assign y_window_2_1_2_fu_750_p2 = (tmp_i_reg_1515 + ap_const_lv8_10);
always @ (posedge ap_clk)
begin
    tmp1_reg_1486[0] <= 1'b0;
    tmp4_reg_1520[0] <= 1'b0;
    tmp_6_i2_reg_1525[0] <= 1'b0;
end



endmodule //image_filter_Loop_1_proc

