// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.4
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#1 "/home/alok/Work/Zedboard/temp/hls/solution1/test.cpp"
#1 "<built-in>"
#1 "<command-line>"
#1 "/home/alok/Work/Zedboard/temp/hls/solution1/test.cpp"






#ifndef HLS_FASTSIM
#include "apatb_axi_stream_counter_range.h"
#endif
#define axi_stream_counter_range(...) AESL_ORIG_DUT_axi_stream_counter_range(__VA_ARGS__)
#6 "/home/alok/Work/Zedboard/temp/hls/solution1/test.cpp"
int axi_stream_counter_range(int count_range, int *counter) {
#pragma HLS INTERFACE axis port=count_range
#pragma HLS INTERFACE axis port=counter

 int counterValue=0;
 for(counterValue=0;counterValue<count_range;counterValue++)
 {
  *counter=counterValue;

 }

 return 0;
}
#undef axi_stream_counter_range

#18 "/home/alok/Work/Zedboard/temp/hls/solution1/test.cpp"
