// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.4
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#1 "/home/alok/Vivado_Projects/MSadri/AXI_STREAM_HLS_S06/HLS/simple_axi_stream_counter/test.cpp"
#1 "<built-in>"
#1 "<command-line>"
#1 "/home/alok/Vivado_Projects/MSadri/AXI_STREAM_HLS_S06/HLS/simple_axi_stream_counter/test.cpp"




int axi_stream_counter(int *);


#ifndef HLS_FASTSIM
#7 "/home/alok/Vivado_Projects/MSadri/AXI_STREAM_HLS_S06/HLS/simple_axi_stream_counter/test.cpp"
int main()
{
  int i;
  int y;
  for(i=0;i<100;i++)
  {
   axi_stream_counter(&y);
  }
  return 0;

}
#endif
#17 "/home/alok/Vivado_Projects/MSadri/AXI_STREAM_HLS_S06/HLS/simple_axi_stream_counter/test.cpp"
